/**
 * Type-level snapshot of the public API. `tsconfig.api.json` emits declarations
 * (with `isolatedDeclarations`, so every exported signature is spelled out in the
 * source); for each package entry point, its declaration file and every
 * declaration file it reaches through relative imports are concatenated into
 * `api/<entry>.d.ts`, which is committed. Any change to a public type shows up as
 * a diff there and fails this test until accepted with
 *
 *   UPDATE_API_SNAPSHOT=1 bun test tests/api-snapshot.test.ts
 */
import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";

const PACKAGE_DIR = resolve(import.meta.dir, "..");
const UPDATE_ENV = "UPDATE_API_SNAPSHOT";

/** Snapshot name → entry declaration file, relative to the emitted `src`. */
const ENTRIES: Record<string, string> = {
  index: "index.d.ts",
  advanced: "advanced.d.ts",
  toncenter: "plugins/toncenter/index.d.ts",
  parse: "parse/index.d.ts",
  webhook: "webhook/index.d.ts",
  cli: "cli.d.ts",
};

const RELATIVE_SPECIFIER = /(?:from\s+|import\()"(\.{1,2}\/[^"]+)"/g;

function emitDeclarations(): string {
  const outDir = mkdtempSync(join(tmpdir(), "ton-watch-api-"));
  // `isolatedDeclarations` is enforced by `bun run typecheck`; off here, a file
  // that violates it is still emitted (identically otherwise) and diffed. The exit
  // code is ignored for the same reason: type errors are the typecheck's job.
  const args = ["-p", "tsconfig.api.json", "--isolatedDeclarations", "false", "--outDir", outDir];
  Bun.spawnSync(["bunx", "tsc", ...args], {
    cwd: PACKAGE_DIR,
    stdout: "ignore",
    stderr: "ignore",
  });
  return outDir;
}

function resolveDeclaration(fromFile: string, specifier: string): string {
  const base = resolve(dirname(fromFile), specifier.replace(/\.ts$/, ""));
  for (const candidate of [`${base}.d.ts`, join(base, "index.d.ts")]) {
    if (Bun.file(candidate).size > 0) return candidate;
  }
  throw new Error(`cannot resolve ${specifier} from ${fromFile}`);
}

/** The entry's declarations plus everything they reach, one file after another. */
function snapshotOf(outDir: string, entry: string): string {
  const seen = new Set<string>();
  const pending = [join(outDir, entry)];
  while (pending.length > 0) {
    const file = pending.pop()!;
    if (seen.has(file)) continue;
    seen.add(file);
    for (const [, specifier] of readFileSync(file, "utf8").matchAll(RELATIVE_SPECIFIER)) {
      pending.push(resolveDeclaration(file, specifier!));
    }
  }
  const entryFile = join(outDir, entry);
  const files = [entryFile, ...[...seen].filter((file) => file !== entryFile).sort()];
  const header = `// API snapshot of ${entry}; generated by tests/api-snapshot.test.ts (${UPDATE_ENV}=1).\n`;
  return (
    header +
    files
      .map(
        (file) => `\n// ---- ${relative(outDir, file)}\n${readFileSync(file, "utf8").trimEnd()}\n`,
      )
      .join("")
  );
}

describe("API snapshot", () => {
  const outDir = emitDeclarations();
  const update = process.env[UPDATE_ENV] === "1";
  try {
    for (const [name, entry] of Object.entries(ENTRIES)) {
      const actual = snapshotOf(outDir, entry);
      const path = join(PACKAGE_DIR, "api", `${name}.d.ts`);
      if (update) writeFileSync(path, actual);
      test(`api/${name}.d.ts matches the emitted declarations`, () => {
        const committed = Bun.file(path).size > 0 ? readFileSync(path, "utf8") : "";
        expect(actual).toBe(committed);
      });
    }
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
});
