// API snapshot of cli.d.ts; generated by tests/api-snapshot.test.ts (UPDATE_API_SNAPSHOT=1).

// ---- cli.d.ts
/**
 * Runs one `ton-watch` command, by default the one on this process's command
 * line, configured from `process.env`. Long-running commands (`run`, `deliver`)
 * return once the service is up and exit the process on SIGINT/SIGTERM; the
 * others exit the process when done. A failure is logged and exits with code 1.
 */
export declare function run(argv?: string[], env?: Record<string, string | undefined>): Promise<void>;
