// API snapshot of index.d.ts; generated by tests/api-snapshot.test.ts (UPDATE_API_SNAPSHOT=1).

// ---- index.d.ts
/**
 * ton-watch: an embeddable, ordered transaction indexer for a set of TON addresses.
 *
 * Start with `TonWatch`: give it a store (`PgStore` or `MemoryStore`) and a source
 * (`LiteSource`), add addresses, and register consumers with `process()`.
 *
 * Other entry points:
 * - `@ton/watch/toncenter`: the toncenter history plug-in.
 * - `@ton/watch/parse`: typed views of transactions (transfers, jettons, NFTs).
 * - `@ton/watch/webhook`: verifying the service's webhook deliveries.
 * - `@ton/watch/advanced` (experimental): the building blocks behind `TonWatch`,
 *   for custom stores, sources and setups.
 *
 * Every error ton-watch throws on purpose is a `TonWatchError`; match on its
 * `code` with `isTonWatchError`.
 *
 * @module
 */
export type { Consumer } from "./consumer/consumer";
export { ConsumerLockedError, CursorConflictError } from "./consumer/errors";
export type { AddressLag, ConsumerEventMap, ConsumerLag, ConsumerStatus, FailurePolicy, HandlerContext, HandlerFailure, LockMode, ProcessOptions, RewindOptions, RewindTarget, TxHandler, } from "./consumer/types";
export { type AddressInput, toRawAddress } from "./core/address";
export { type ErrorKind, isTonWatchError, SourceError, type SourceErrorCode, TonWatchError, type TonWatchErrorCode, } from "./core/errors";
export type { AddressState, IndexedTx, TxId, TxRecord } from "./core/types";
export type { DetectMode, IndexingOptions, SplitOptions } from "./indexer/options";
export type { AddressStatus } from "./indexer/status";
export { Metrics } from "./metrics/metrics";
export type { HistoryOptions } from "./source/history";
export { LiteSource, type LiteSourceOptions } from "./source/liteserver/lite-source";
export type { ServerStats } from "./source/liteserver/server-pool";
export type { BlockRef, ChainTip, ShardTop } from "./source/source";
export type { ConsumerOrder, ConsumerRecord, CursorState, DeadLetter, DeadLetterFilter, } from "./stores/consumer-state";
export { MemoryStore } from "./stores/memory/memory-store";
export type { PgDatabase, PgQueryable } from "./stores/pg/database";
export { MigrationError, type MigrationErrorCode } from "./stores/pg/migrator";
export { PgStore, type PgStoreOptions } from "./stores/pg/pg-store";
export { type AddAddressOptions, type Health, type HealthOptions, type RemoveAddressOptions, TonWatch, type TonWatchEventMap, type TonWatchOptions, } from "./ton-watch";
export { consoleLogger, type Logger, type LogLevel, silentLogger } from "./util/logger";

// ---- consumer/consumer.d.ts
import { EventEmitter } from "node:events";
import { type AddressInput } from "../core/address";
import { Metrics } from "../metrics/metrics";
import type { DeadLetter, DeadLetterFilter } from "../stores/consumer-state";
import { type Store } from "../stores/store";
import { type Logger } from "../util/logger";
import type { ConsumerEventMap, ConsumerLag, ConsumerStatus, ConsumerWakeEvents, ProcessOptions, RewindOptions, RewindTarget, TxHandler } from "./types";
/**
 * What a `Consumer` is wired to besides its store; `TonWatch` passes its own.
 * @experimental
 */
export interface ConsumerDeps {
    /** Wake up on these instead of waiting for the next poll. */
    events?: ConsumerWakeEvents;
    logger?: Logger;
    metrics?: Metrics;
}
/**
 * Hands indexed transactions to a handler strictly in chain order, never past a
 * gap, and persists the position after each one so restarts resume where they
 * stopped. A failing handler stops its address (or, in global order, the whole
 * stream) and is retried with backoff; with `onError: "skip"` or `"dead-letter"`
 * it is given up on after `maxAttempts`, or at once if `isRetryable` says so.
 *
 * Only one instance of a consumer name delivers at a time: rounds run under the
 * store's consumer lock (see `ProcessOptions.lock`).
 *
 * Emits `handlerError`, `skip` and `deadLetter` (see `ConsumerEventMap`).
 *
 * Get one from `TonWatch.process()`. Constructing one directly (exported from
 * `@ton/watch/advanced`) is experimental.
 */
export declare class Consumer<Db = unknown> extends EventEmitter<ConsumerEventMap> {
    readonly name: string;
    private readonly store;
    /**
     * Stored as `TxHandler<never>` so that `Consumer<PgQueryable>` is still a
     * `Consumer` (a function-typed field would make `Db` invariant); see `handle`.
     */
    private readonly handler;
    private readonly settings;
    /** Raw addresses to deliver; null for all. */
    private readonly onlyAddresses;
    private readonly logger;
    private readonly metrics;
    private readonly events;
    private readonly lanes;
    /** Lanes mirror the store only while the lock is held without a break; false = reload. */
    private lanesLoaded;
    /** Rounds and rewinds, one at a time. */
    private readonly serial;
    /** Pending requests for the current round to end early (a rewind waiting for it). */
    private yieldRequests;
    private lifecycle;
    /** Whether the latest `start()` / `stop()` call was a start. */
    private wanted;
    /** Lifecycle transitions, one at a time. */
    private readonly transitions;
    /** The latest `start()`'s lock attempt, for `ready()`. */
    private startAttempt;
    private wakeUp;
    /** Something changed while a round was running: start another right away. */
    private wakePending;
    private delivered;
    private lastLag;
    private lagMeasuredAt;
    private unsubscribe;
    constructor(name: string, store: Store<Db>, handler: TxHandler<Db>, options?: ProcessOptions, deps?: ConsumerDeps);
    /**
     * Takes the consumer lock and starts delivering in the background. Await
     * `ready()` to learn whether it got the lock. Calling it while started does
     * nothing; while a `stop()` is finishing, it starts again once that is done.
     */
    start(): this;
    /**
     * Settles once `start()` made its first attempt at the lock: rejects with
     * `ConsumerLockedError` if another instance holds it (`lock: "fail"`), otherwise
     * resolves — delivering, or with `lock: "wait"` waiting for the lock.
     */
    ready(): Promise<void>;
    /**
     * Stops after the transaction being handled (if any) is committed, then releases
     * the lock. Resolves once stopped; a `start()` still taking the lock is undone.
     */
    stop(): Promise<void>;
    /** Looks for new transactions now instead of at the next poll. */
    wake(): void;
    status(): ConsumerStatus;
    /**
     * Runs one delivery round. Resolves to the number of transactions the cursors
     * moved past (delivered, skipped or dead-lettered). Outside `start()` it takes
     * the consumer lock for the round and releases it afterwards. Rejects with
     * `CursorConflictError` if a cursor was moved by someone else meanwhile (the
     * next round resumes from there).
     */
    runOnce(): Promise<number>;
    /**
     * Measures how far behind the consumer is (see `ConsumerLag`) and publishes it as
     * `status().lag` and the `ton_watch_consumer_lag_*` gauges.
     */
    lag(): Promise<ConsumerLag>;
    /**
     * Moves the cursors to `to` (on `addresses`, default all the consumer has) and
     * clears their failure counts. A running consumer applies it between rounds: the
     * current round ends after the transaction being handled. Rejects with
     * `ConsumerLockedError` if another instance runs. Dead letters are kept.
     */
    rewind(to: RewindTarget, options?: RewindOptions): Promise<void>;
    /** This consumer's dead letters, oldest first. */
    deadLetters(filter?: Omit<DeadLetterFilter, "consumer">): Promise<DeadLetter[]>;
    /** Deletes a dead letter without redelivering it. False if there was none. */
    discardDeadLetter(address: AddressInput, lt: bigint): Promise<boolean>;
    /**
     * Hands a dead-lettered transaction to the handler again (`ctx.replay` is true),
     * then deletes the dead letter — atomically with the handler's `ctx.db` writes
     * when transactional. It is out of order by nature and may run alongside live
     * delivery. If the handler throws, the dead letter stays (with the new error)
     * and the error is rethrown — unless it was discarded meanwhile, which stands.
     *
     * Rejects with code `DEAD_LETTER_NOT_FOUND` if there is no such dead letter (or it
     * was discarded during the replay), `TRANSACTION_NOT_FOUND` if the transaction is
     * no longer stored.
     */
    replayDeadLetter(addressInput: AddressInput, lt: bigint): Promise<void>;
    /** The run that is delivering (not stopping), if any. */
    private activeRun;
    /** Transition to running, unless a `stop()` came after the `start()`. */
    private begin;
    /** Transition to stopped: ends the loop, then releases the run's lock (once). */
    private end;
    private subscribe;
    private releaseLock;
    /**
     * Runs `fn` under the consumer lock: the one a started consumer holds, or one
     * taken for this call only.
     */
    private whileLocked;
    /** The run's lock, re-taken if it was lost; null while another instance has it. */
    private ensureLock;
    /**
     * A round keeps delivering while its lock is held, no cursor conflict occurred,
     * nothing (a rewind) waits for it, and — once started — until `stop()`.
     */
    private shouldContinue;
    private runLoop;
    private measureLagIfDue;
    /** Time until the earliest halted lane may retry; Infinity if none is halted. */
    private msUntilNextRetry;
    private sleepUntilWoken;
    private round;
    /**
     * Creates lanes for new addresses and drops those of addresses no longer
     * delivered (removed), so their halts hold nothing back. After the lock was
     * (re)taken, first reloads every cursor and failure count from the store; a halt
     * survives the reload if its cursor did not move.
     */
    private syncLanes;
    /** The lane's position, loading or initializing (and persisting) it on first use. */
    private cursorFor;
    /**
     * Where a new lane begins. "now" is resolved (and persisted) the first round the
     * consumer sees the address, also before anything is indexed for it, so it means
     * "indexed after the consumer started" in either order.
     */
    private initialCursor;
    private handle;
    /** Runs `fn` in a store transaction if the consumer is transactional and the store has them. */
    private withDeliveryStore;
    /**
     * Hands one transaction to the handler and commits the cursor. A cursor
     * conflict ends the round and makes the next one reload every lane.
     */
    private deliver;
    private attempt;
    /**
     * Moves the stored cursor from where this lane last saw it to `lt`; throws
     * `CursorConflictError` (rolling back the enclosing transaction) if it is not
     * there any more.
     */
    private moveCursor;
    private advance;
    /**
     * Counts the failure, then halts the lane or, past `maxAttempts` or on a
     * non-retryable error, gives up on the transaction.
     */
    private handleFailure;
    /** Moves past a failing transaction, recording it as a dead letter first if so configured. */
    private giveUp;
    private halt;
    /**
     * Each address up to its own frontier, `concurrency` addresses at a time. The
     * round ends only once every worker has stopped, so no lane is ever delivered by
     * two rounds at once; a store error fails the round after that.
     */
    private deliverPerAddress;
    /** One batch of one address, up to its frontier. Resolves to the number moved past. */
    private deliverLane;
    /**
     * All addresses merged by (lt, address), up to the watermark: the lowest point
     * up to which every address is known complete. Any halted address halts all;
     * a transaction given up on (skip / dead letter) does not.
     */
    private deliverGlobal;
}

// ---- consumer/errors.d.ts
import { TonWatchError } from "../core/errors";
/** Another instance holds the single-instance lock of this consumer name. Code `CONSUMER_LOCKED`. */
export declare class ConsumerLockedError extends TonWatchError<"CONSUMER_LOCKED"> {
    name: string;
    readonly consumer: string;
    constructor(consumer: string);
}
/**
 * A consumer's cursor was not where this instance last saw it: another writer moved
 * it (an instance that took over after this one lost its lock, a rewind without the
 * lock), or an earlier commit went through without this process learning so. The
 * delivery is rolled back (with a transactional store), the round ends, and the
 * consumer reloads its positions before delivering again. Code `CURSOR_CONFLICT`.
 */
export declare class CursorConflictError extends TonWatchError<"CURSOR_CONFLICT"> {
    name: string;
    readonly consumer: string;
    readonly address: string;
    /** Where this instance expected the cursor; null for none yet. */
    readonly expected: bigint | null;
    constructor(consumer: string, address: string, expected: bigint | null);
}

// ---- consumer/types.d.ts
import type { AddressInput } from "../core/address";
import type { IndexedTx } from "../core/types";
import type { ConsumerOrder, DeadLetter } from "../stores/consumer-state";
export interface HandlerContext<Db = unknown> {
    /** Name of the consumer delivering the transaction. */
    consumer: string;
    /** Raw address the transaction belongs to. */
    address: string;
    /**
     * With a transactional store (`PgStore`), the database transaction the cursor is
     * committed in. Write your own effects through it and they commit exactly once
     * together with the delivery position. Typed after the store: `PgQueryable`
     * with `PgStore`; absent with `MemoryStore`, with `transactional: false`, and
     * in `replayDeadLetter` calls that run outside a transaction.
     */
    db?: Db;
    /** True when a dead letter is being replayed (out of order, see `replayDeadLetter`). */
    replay: boolean;
}
/** Called once per transaction, in order. Throwing fails the delivery (see `ProcessOptions.onError`). */
export type TxHandler<Db = unknown> = (tx: IndexedTx, ctx: HandlerContext<Db>) => Promise<void> | void;
/**
 * What to do with a transaction whose handler keeps failing:
 * - `"retry"`: retry it forever with backoff; nothing is ever skipped.
 * - `"skip"`: after `maxAttempts`, move past it.
 * - `"dead-letter"`: after `maxAttempts`, record it as a dead letter and move past it.
 */
export type FailurePolicy = "retry" | "skip" | "dead-letter";
/** What a consumer does when another instance of the same name holds the lock. */
export type LockMode = "fail" | "wait";
export interface ProcessOptions {
    /**
     * Where to begin for an address this consumer has not seen before:
     * `"earliest"` (default) everything since the address's startLt, `"now"` only what
     * is indexed after this point, or an lt (exclusive). Ignored once a position is stored.
     */
    from?: "earliest" | "now" | bigint;
    /** Addresses to deliver; default every tracked address, including ones added later. */
    addresses?: readonly AddressInput[];
    /**
     * `"address"` (default): each address in lt order, addresses independent of each
     * other. `"global"`: one stream in (lt, address) order, released up to the
     * watermark — the lowest complete-up-to point among the addresses.
     */
    order?: ConsumerOrder;
    /** Transactions read from the store per query. Default 100. */
    batchSize?: number;
    /** Addresses processed in parallel in `"address"` order. Default 8. */
    concurrency?: number;
    /** How often to look for new data when no indexer event arrives. Default 1000ms. */
    pollMs?: number;
    /** First retry delay after a handler failure; doubles per failure. Default 1s. */
    retryMinMs?: number;
    /** Longest retry delay after a handler failure. Default 60s. */
    retryMaxMs?: number;
    /** Commit handler effects and cursor atomically when the store supports it. Default true. */
    transactional?: boolean;
    /** Policy for a transaction whose handler keeps failing. Default `"retry"`. */
    onError?: FailurePolicy;
    /** Failed attempts before `"skip"` or `"dead-letter"` gives up. Default 5. */
    maxAttempts?: number;
    /**
     * Whether a handler error may go away on retry. With `"skip"` or `"dead-letter"`,
     * a transaction failing with a non-retryable error is given up on at once instead
     * of after `maxAttempts`; `"retry"` retries it regardless. Default: every error is
     * retryable.
     */
    isRetryable?: (error: unknown) => boolean;
    /**
     * When another instance runs under the same name: `"fail"` (default) rejects
     * `start()` / `runOnce()` with `ConsumerLockedError`; `"wait"` waits for the lock.
     */
    lock?: LockMode;
    /** How often a started consumer measures its lag (status and metrics); 0 = never. Default 15s. */
    lagIntervalMs?: number;
}
/** How far a consumer is behind on one address. */
export interface AddressLag {
    address: string;
    cursor: bigint;
    /** Deliverable transactions not yet delivered. */
    transactions: number;
    /** Lt of the newest deliverable transaction minus the cursor; 0 when caught up. */
    lt: bigint;
    /** Age of the oldest deliverable transaction not yet delivered; 0 when caught up. */
    seconds: number;
}
/**
 * How far a consumer is behind what it may deliver: each address's frontier, or in
 * global order the watermark. Indexing lag is separate (`AddressStatus.lagSeconds`).
 */
export interface ConsumerLag {
    /** Sum over the addresses. */
    transactions: number;
    /** Maximum over the addresses. */
    lt: bigint;
    /** Maximum over the addresses. */
    seconds: number;
    addresses: AddressLag[];
}
export interface ConsumerStatus {
    name: string;
    running: boolean;
    /** Started in `lock: "wait"` mode (or lost its lock) and waiting for another instance to stop. */
    waitingForLock: boolean;
    /** Transactions delivered since this process started. */
    delivered: number;
    /** Last measured lag; null before the first measurement. */
    lag: ConsumerLag | null;
    addresses: {
        address: string;
        /** Lt of the last delivered transaction. */
        cursor: bigint | null;
        /** Waiting to retry a failed handler. */
        halted: boolean;
        /** Failed attempts on the next transaction (persisted across restarts). */
        failures: number;
        lastError?: string;
    }[];
}
/** One failed handler call. */
export interface HandlerFailure {
    consumer: string;
    address: string;
    lt: bigint;
    hash: Buffer;
    error: unknown;
    /** Failed attempts on this transaction so far, this one included. */
    attempts: number;
    /** What happens next: retried later, or given up on as `"skip"` / `"dead-letter"`. */
    action: FailurePolicy;
}
/** Events emitted by `Consumer`, with their listener arguments. */
export interface ConsumerEventMap {
    /** A handler call failed. */
    handlerError: [failure: HandlerFailure];
    /** A transaction was skipped after `maxAttempts` (`onError: "skip"`). */
    skip: [letter: DeadLetter];
    /** A transaction was dead-lettered after `maxAttempts` (`onError: "dead-letter"`). */
    deadLetter: [letter: DeadLetter];
}
/**
 * Where `rewind` moves a cursor: `"earliest"` (the address's startLt), `"now"` (its
 * frontier), or right after an lt.
 */
export type RewindTarget = "earliest" | "now" | bigint;
export interface RewindOptions {
    /** Addresses to move; default every address the consumer has a cursor on. */
    addresses?: readonly AddressInput[];
}
/**
 * Indexer events a consumer wakes up on (an `Indexer`, or any `EventEmitter`).
 * @experimental
 */
export interface ConsumerWakeEvents {
    on(event: "frontier" | "synced", listener: () => void): unknown;
    off(event: "frontier" | "synced", listener: () => void): unknown;
}

// ---- core/address.d.ts
import { Address } from "@ton/core";
/**
 * An address as ton-watch accepts it: an `@ton/core` `Address`, or a string in
 * friendly (`EQ…`/`UQ…`) or raw (`<workchain>:<hex>`, either hex case) form.
 * Addresses ton-watch hands out are always lowercase raw strings.
 */
export type AddressInput = Address | string;
/**
 * Normalizes an address to its lowercase raw form `<workchain>:<hex>`, the only
 * form ton-watch stores and returns. Throws `INVALID_ADDRESS` if it is not one.
 */
export declare function toRawAddress(address: AddressInput): string;
/** Workchain of a raw address. */
export declare function workchainOf(rawAddress: string): number;
/** Short form for log lines: the first and last four characters. */
export declare function abbreviateAddress(address: string): string;

// ---- core/errors.d.ts
/**
 * Every error ton-watch throws on purpose carries one of these codes. The codes
 * are the stable contract: match on them (with `isTonWatchError`), not on
 * messages or class identity — messages may change in any release, a code is only
 * removed or repurposed in a major one.
 *
 * - `INVALID_OPTION`: an option or argument has a value that cannot work.
 * - `INVALID_ADDRESS`: an address is neither a valid friendly nor raw address.
 * - `UNKNOWN_ADDRESS`: the address is not tracked by the store.
 * - `UNKNOWN_CONSUMER`: no consumer of that name (in the store, or registered in
 *   this process where the operation needs a local one).
 * - `CONSUMER_REGISTERED`: a consumer of that name is already registered in this
 *   `TonWatch`.
 * - `CONSUMER_LOCKED`: another instance holds the consumer's lock (`ConsumerLockedError`).
 * - `CURSOR_CONFLICT`: a consumer's cursor was moved by someone else (`CursorConflictError`).
 * - `DEAD_LETTER_NOT_FOUND`: no such dead letter (any more).
 * - `TRANSACTION_NOT_FOUND`: the transaction is no longer stored.
 * - `CLOSED`: the `TonWatch` was closed.
 * - `PG_POOL_TOO_SMALL`: a `pg.Pool` has too few connections for the running consumers.
 * - `MIGRATION_MODIFIED`, `MIGRATION_TOO_NEW`, `MIGRATION_DIVERGED`: `migrate()`
 *   refused the schema (`MigrationError`).
 * - `SOURCE_*`: a chain request failed (`SourceError`); the suffix is its `ErrorKind`.
 */
export type TonWatchErrorCode = "INVALID_OPTION" | "INVALID_ADDRESS" | "UNKNOWN_ADDRESS" | "UNKNOWN_CONSUMER" | "CONSUMER_REGISTERED" | "CONSUMER_LOCKED" | "CURSOR_CONFLICT" | "DEAD_LETTER_NOT_FOUND" | "TRANSACTION_NOT_FOUND" | "CLOSED" | "PG_POOL_TOO_SMALL" | "MIGRATION_MODIFIED" | "MIGRATION_TOO_NEW" | "MIGRATION_DIVERGED" | SourceErrorCode;
/**
 * Base class of every error ton-watch throws on purpose. Check `code` (see
 * `TonWatchErrorCode`) through `isTonWatchError`, which unlike `instanceof` also
 * works when two copies of ton-watch are loaded. The underlying error, if any, is
 * the standard `cause`.
 */
export declare class TonWatchError<Code extends TonWatchErrorCode = TonWatchErrorCode> extends Error {
    name: string;
    readonly code: Code;
    constructor(code: Code, message: string, options?: {
        cause?: unknown;
    });
}
/**
 * Whether `error` was thrown by ton-watch (any copy of it) and, if given, has
 * `code`.
 *
 * ```ts
 * if (isTonWatchError(error, "CONSUMER_LOCKED")) { … }
 * ```
 */
export declare function isTonWatchError<Code extends TonWatchErrorCode = TonWatchErrorCode>(error: unknown, code?: Code): error is TonWatchError<Code>;
/** What went wrong with a chain request, as far as retry policy is concerned. */
export type ErrorKind = "rate_limit" | "timeout" | "archive_unavailable" | "not_ready" | "bad_response" | "network" | "unknown";
/** `SourceError` codes: `SOURCE_` plus the upper-cased `ErrorKind`. */
export type SourceErrorCode = `SOURCE_${Uppercase<ErrorKind>}`;
/** An error from a transaction source, already classified (`kind`, and `code` derived from it). */
export declare class SourceError extends TonWatchError<SourceErrorCode> {
    name: string;
    readonly kind: ErrorKind;
    constructor(kind: ErrorKind, message: string, cause?: unknown);
}
/** Maps a liteserver / transport error to a kind the retry policy understands. */
export declare function classifyError(error: unknown): ErrorKind;
/**
 * The message of anything thrown: `Error`s, plain objects with a `message`, or other
 * values. An empty message falls back to the inner errors of an `AggregateError`
 * (what `pg` throws when every address of a host refuses), then to the error `code`.
 */
export declare function errorMessage(error: unknown): string;

// ---- core/types.d.ts
import { type Transaction } from "@ton/core";
/** Identifies one transaction of an account: logical time + cell hash. */
export interface TxId {
    lt: bigint;
    hash: Buffer;
}
/**
 * A transaction as the indexer stores it. Every account transaction links to the
 * previous one through `prevLt`/`prevHash`; that link is what lets writes land in
 * any order and still be checked for completeness. `prevLt === 0n` marks the
 * account's very first transaction.
 */
export interface TxRecord {
    /** Raw address, `<workchain>:<hex>`. */
    address: string;
    lt: bigint;
    hash: Buffer;
    prevLt: bigint;
    prevHash: Buffer;
    /** Unix time of the block the transaction is in. */
    utime: number;
    /** The transaction cell serialized as a BOC. */
    boc: Buffer;
}
/** What the store knows about one tracked address. */
export interface AddressState {
    /** Raw address, `<workchain>:<hex>`. */
    address: string;
    /** Transactions with `lt <= startLt` are out of scope and never fetched or delivered. */
    startLt: bigint;
    active: boolean;
    /** Newest stored transaction. */
    head: TxId | null;
    /**
     * Newest transaction such that every transaction between `startLt` and it is
     * stored. Ordered delivery never goes past this point.
     */
    frontier: TxId | null;
    /**
     * Chain logical time up to which the address is known complete, even when it
     * had no transactions: no transaction with `lt <= syncedLt` is missing.
     * Used for the cross-address watermark.
     */
    syncedLt: bigint;
    /** Chain unix time at which `syncedLt` was observed, for lag reporting. */
    syncedUtime: number | null;
}
/** A missing range below a stored transaction whose previous transaction is not stored. */
export interface Gap {
    address: string;
    /** The stored transaction whose `prev` link is unsatisfied. */
    aboveLt: bigint;
    /** Where to resume fetching (the missing transaction). */
    prevLt: bigint;
    prevHash: Buffer;
    /** Highest stored lt below the gap, or the address `startLt`. Fetching stops here. */
    floorLt: bigint;
}
/** A transaction handed to consumer code. */
export interface IndexedTx extends TxRecord {
    /** Parsed `@ton/core` transaction (parsed lazily, cached). */
    readonly transaction: Transaction;
}
/** Wraps a stored record for delivery; the `transaction` is parsed on first access. */
export declare function toIndexedTx(record: TxRecord): IndexedTx;
/** Whether two transaction ids are the same; two missing ids are equal. */
export declare function txIdEquals(a: TxId | null | undefined, b: TxId | null | undefined): boolean;
/** The lt up to which every transaction of the address is stored (its watermark input). */
export declare function completeUpTo(state: AddressState): bigint;
/** The lowest `completeUpTo` among `states`: every transaction at or below it is stored. Null if empty. */
export declare function watermarkOf(states: readonly AddressState[]): bigint | null;

// ---- indexer/events.d.ts
import type { EventEmitter } from "node:events";
import type { ErrorKind } from "../core/errors";
import type { ChainTip } from "../source/source";
/** Events emitted by `Indexer`, with their listener arguments. */
export interface IndexerEventMap {
    /** A detection and maintenance round finished. */
    tick: [tip: ChainTip];
    /** An address's frontier moved forward: new transactions are deliverable. */
    frontier: [address: string, lt: bigint];
    /** An address is known complete up to a newer chain lt. */
    synced: [address: string, syncLt: bigint];
    /** A page fetch failed and will be retried. */
    fetchError: [address: string, kind: ErrorKind, error: unknown];
}
/** The emitting side, as handed to the indexer's components. */
export type IndexerEmitter = Pick<EventEmitter<IndexerEventMap>, "emit">;

// ---- indexer/options.d.ts
import type { Metrics } from "../metrics/metrics";
import type { HistoryOptions } from "../source/history";
import type { TxSource } from "../source/source";
import type { Store } from "../stores/store";
import type { Logger } from "../util/logger";
/**
 * How to find addresses with new transactions:
 * - `poll`: one account-state call per address, idle addresses polled less often.
 * - `blocks`: list the transactions of every new shard block once and match
 *   watched addresses; cost does not grow with the number of addresses.
 * - `auto`: `blocks` from `autoBlocksThreshold` addresses on, `poll` below.
 */
export type DetectMode = "poll" | "blocks" | "auto";
/** Splitting of long missing ranges into parallel pieces. */
export interface SplitOptions {
    /** Only ranges estimated at this many transactions or more are split. Default 1000. */
    minTxs?: number;
    /** Aim for pieces of about this many transactions. Default 400. */
    targetTxs?: number;
    /** At most this many pieces per range. Default 32. */
    maxParts?: number;
}
/** Indexing tuning, shared by `TonWatchOptions` and `IndexerOptions`. */
export interface IndexingOptions {
    /** Pages fetched in parallel across all addresses and ranges. Default 16. */
    concurrency?: number;
    /** How often to look at the chain tip. Default 1000ms. */
    tickMs?: number;
    /** See `DetectMode`. Default `auto`. */
    detect?: DetectMode;
    /** Address count from which `auto` uses `blocks`. Default 50. */
    autoBlocksThreshold?: number;
    /** Poll mode: an address that keeps not changing is polled at most this rarely. Default 30s. */
    maxIdlePollMs?: number;
    /** Blocks mode: every address is also checked directly at least this often. Default 10 min. */
    reconcileMs?: number;
    /** Every address is rescanned for gaps this often (changed ones every tick). Default 60s. */
    gapScanMs?: number;
    /** First retry delay of a failing range fetch; doubles per failure. Default 1s. */
    retryMinMs?: number;
    /** Longest retry delay of a failing range fetch. Default 60s. */
    retryMaxMs?: number;
    /** Retry delay for history no server can serve (archive miss). Default 10 min. */
    archiveRetryMs?: number;
    /**
     * Cut long missing ranges into parallel pieces (needs `source.findTxNear`).
     * `false` disables it.
     */
    split?: SplitOptions | false;
    /** Optional history plug-in (see `HistorySource`), e.g. `@ton/watch/toncenter`. */
    history?: HistoryOptions;
    /**
     * Export per-address gauges (`ton_watch_address_lag_seconds`,
     * `ton_watch_address_gaps_open`), one series per address. Default false: with
     * many addresses they multiply the series a Prometheus server has to keep.
     */
    addressMetrics?: boolean;
}
/**
 * Options of a standalone `Indexer` (`@ton/watch/advanced`).
 * @experimental
 */
export interface IndexerOptions<Db = unknown> extends IndexingOptions {
    store: Store<Db>;
    source: TxSource;
    metrics?: Metrics;
    logger?: Logger;
}
/** `IndexerOptions` tuning values with defaults applied. */
export interface IndexerSettings {
    concurrency: number;
    tickMs: number;
    detect: DetectMode;
    autoBlocksThreshold: number;
    maxIdlePollMs: number;
    reconcileMs: number;
    gapScanMs: number;
    retryMinMs: number;
    retryMaxMs: number;
    archiveRetryMs: number;
    addressMetrics: boolean;
}
export declare const DEFAULT_SETTINGS: IndexerSettings;
export declare const DEFAULT_SPLIT: Required<SplitOptions>;
/** Tuning values with defaults applied. Throws on a `concurrency` that would start no work. */
export declare function resolveSettings(options: IndexingOptions): IndexerSettings;
/** Split settings, or null when splitting is off or the source cannot find split points. */
export declare function resolveSplit(options: IndexerOptions<unknown>): Required<SplitOptions> | null;
/** History plug-in settings, or null when none is configured or it is switched off. */
export declare function resolveHistory(options: IndexingOptions): Required<HistoryOptions> | null;

// ---- indexer/status.d.ts
import type { Metrics } from "../metrics/metrics";
import type { ChainTip } from "../source/source";
import type { TrackedAddress } from "./tracked-address";
import { type Walk } from "./walk";
/** Indexing progress of one address. */
export interface AddressStatus {
    address: string;
    /** Newest stored transaction lt. */
    head: bigint | null;
    /** Newest lt with everything below it stored. */
    frontier: bigint | null;
    syncedLt: bigint;
    /** Seconds between the chain tip and the last time the address was known complete. */
    lagSeconds: number | null;
    gapsOpen: number;
    /** Missing ranges being fetched. */
    walks: number;
    /** Walks waiting on history no server could serve. */
    stuck: number;
}
export declare function addressStatus(tracked: TrackedAddress, walks: Walk[], tip: ChainTip | null): AddressStatus;
/**
 * Publishes indexer-wide gauges and, if `perAddress`, per-address lag and gap
 * gauges. Per-address series are rebuilt each time, so a removed address loses
 * its series and an address whose lag is unknown has no lag series.
 */
export declare function recordGauges(metrics: Metrics, statuses: AddressStatus[], walks: Walk[], perAddress: boolean): void;

// ---- indexer/tracked-address.d.ts
import type { AddressState, TxId } from "../core/types";
/** An address's on-chain last transaction as of a chain tip. */
export interface ChainObservation {
    lastTx: TxId | null;
    syncLt: bigint;
    utime: number;
}
/** The indexer's in-memory view of one address. */
export interface TrackedAddress {
    /** Last state read from the store, updated in place as the indexer advances it. */
    state: AddressState;
    /** Unset until the address's last transaction has been read once. */
    observed?: ChainObservation;
    /** Poll mode: earliest time (ms) of the next poll. */
    nextPollAt: number;
    /** Poll mode: polls in a row that found no change. */
    idleStreak: number;
    /** Last time (ms) the on-chain last tx was read directly (not via block listing). */
    verifiedAt: number;
    /**
     * Set while a reconciliation poll is in flight: what block listing believed the
     * last transaction was. `undefined` when not reconciling.
     */
    reconcilingFrom?: TxId | null;
    /** Frontier and gaps need rechecking at the next maintenance round. */
    needsMaintenance: boolean;
    gapsOpen: number;
}
/** The active addresses, mirrored from the store each tick. */
export declare class AddressTable {
    private readonly byAddress;
    get size(): number;
    get(address: string): TrackedAddress | undefined;
    all(): TrackedAddress[];
    addresses(): string[];
    /** Whether any address still lacks a first observation. */
    anyUnobserved(): boolean;
    /**
     * Updates states, starts tracking new addresses and drops ones no longer in
     * `states`. Returns the dropped addresses.
     */
    sync(states: AddressState[]): string[];
}

// ---- indexer/walk.d.ts
import type { ErrorKind } from "../core/errors";
import type { TxId } from "../core/types";
/** `head`: new transactions found by change detection. `gap`: a hole found in the store. */
export type WalkKind = "head" | "gap";
/** A missing range of one address, fetched backwards page by page. */
export interface WalkRange {
    address: string;
    kind: WalkKind;
    /** Next transaction to fetch (newest first). */
    cursor: TxId;
    /** Stop once the chain reaches this lt (it is stored or out of scope). */
    floorLt: bigint;
    /** Where the walk started; everything in (floorLt, topLt] is this walk's job. */
    topLt: bigint;
}
/** A scheduled walk with its progress and retry state. */
export interface Walk extends WalkRange {
    id: number;
    pages: number;
    /** Transactions received so far (density estimate for splitting). */
    fetched: number;
    /** Already split, or a piece of a split. */
    split: boolean;
    /** Consecutive failed page fetches. */
    failures: number;
    lastError?: ErrorKind;
    /** Earliest time (ms) of the next attempt. */
    notBefore: number;
    running: boolean;
}
/**
 * Repeatedly asked for history that no server (including archival ones) has.
 * "Not found" can also mean "not seen yet" on every server asked, so only a
 * repeated miss counts.
 */
export declare function isParked(walk: Walk): boolean;

// ---- metrics/metrics.d.ts
import type { ErrorKind } from "../core/errors";
import { type CounterName, type GaugeName, METRICS, type MetricLabels, type MetricName } from "./registry";
/** Labels argument: omitted for a metric without labels, exactly its labels otherwise. */
type LabelsArg<N extends MetricName> = (typeof METRICS)[N]["labels"] extends readonly [] ? [labels?: undefined] : [labels: MetricLabels<N>];
/**
 * ton-watch's metrics: the counters and gauges listed in `METRICS` (see
 * `registry.ts`), and nothing else.
 *
 * Read them with `toPrometheus()` (served on the service's `/metrics`),
 * `snapshot()`, `get()` or `sum()`. The recording methods are for ton-watch's own
 * components; a `Metrics` passed in through options is shared by them.
 */
export declare class Metrics {
    /** Per metric: series by their label values joined with `\0`. */
    private readonly families;
    /** Sliding window of `[timestampMs, txCount]` for `writeRate()`. */
    private writeSamples;
    constructor();
    /** Current value of one series; 0 if it was never recorded. */
    get<N extends MetricName>(name: N, ...[labels]: LabelsArg<N>): number;
    /** Sum of every series of a metric. */
    sum(name: MetricName): number;
    /** Every series, keyed `name{label="value",...}` as in the Prometheus text. */
    snapshot(): Record<string, number>;
    /** Prometheus text exposition format (0.0.4), with `# HELP` and `# TYPE` per metric. */
    toPrometheus(): string;
    /** @internal Adds `by` to a counter. */
    inc<N extends CounterName>(name: N, ...args: [...LabelsArg<N>, by?: number]): void;
    /** @internal Sets a gauge. */
    set<N extends GaugeName>(name: N, value: number, ...[labels]: LabelsArg<N>): void;
    /** @internal Drops one series of a gauge, or all of them without labels. */
    remove<N extends GaugeName>(name: N, labels?: MetricLabels<N>): void;
    /**
     * @internal Counts a failure of `kind` at `where`: one of `ERROR_SITES`,
     * anything else counts as `other`.
     */
    error(kind: ErrorKind, where: string): void;
    /** @internal Counts a call to the chain; `method` outside `SOURCE_METHODS` counts as `other`. */
    call(method: string): void;
    /** @internal Counts newly stored transactions. */
    txWritten(count: number): void;
    /**
     * @internal Transactions written per second over the last `windowMs`, for
     * health reports. Not exported as a metric: use `rate(ton_watch_tx_written_total[1m])`.
     */
    writeRate(windowMs?: number): number;
    private write;
    /** Families by name, each with its series sorted by label values; empty ones left out. */
    private sortedFamilies;
}
export {};

// ---- metrics/registry.d.ts
/**
 * Every metric ton-watch exports: name, type, help text and label names. This is
 * the contract for dashboards and alerts; `Metrics` refuses anything not listed
 * here, and `toPrometheus()` takes `# HELP` and `# TYPE` from it.
 *
 * Label values are bounded: `address` series exist only with the indexer's
 * `addressMetrics` option (off by default), and `where` / `method` take values
 * from the closed sets below (anything else is reported as `other`).
 */
/** A metric's definition. */
export interface MetricDefinition {
    type: "counter" | "gauge";
    help: string;
    labels: readonly string[];
}
/**
 * Chain calls counted by `ton_watch_source_calls_total{method}`: liteserver
 * methods, and the `TxSource` methods of sources that are not liteservers.
 */
export declare const SOURCE_METHODS: readonly ["getTip", "getAccountState", "getTransactions", "lookupBlock", "listBlockTransactions", "getLastTx", "findTxNear", "getTouchedAccounts", "other"];
export type SourceMethod = (typeof SOURCE_METHODS)[number];
/** Where a failure counted by `ton_watch_errors_total{where}` happened. */
export declare const ERROR_SITES: readonly ["getTip", "getAccountState", "getTransactions", "lookupBlock", "listBlockTransactions", "getLastTx", "findTxNear", "getTouchedAccounts", "walk", "tick", "maintain", "advanceFrontier", "history", "other"];
export type ErrorSite = (typeof ERROR_SITES)[number];
/**
 * The registry. Declared `as const` (not `satisfies`, which isolated declarations
 * cannot see through); tests/metrics/registry.test.ts checks it against
 * `MetricDefinition`.
 */
export declare const METRICS: {
    readonly ton_watch_build_info: {
        readonly type: "gauge";
        readonly help: "Always 1; the version label is the running ton-watch version.";
        readonly labels: readonly ["version"];
    };
    readonly ton_watch_addresses: {
        readonly type: "gauge";
        readonly help: "Addresses being indexed.";
        readonly labels: readonly [];
    };
    readonly ton_watch_tip_seqno: {
        readonly type: "gauge";
        readonly help: "Masterchain seqno of the newest chain tip seen.";
        readonly labels: readonly [];
    };
    readonly ton_watch_tip_utime: {
        readonly type: "gauge";
        readonly help: "Unix time (seconds) of the newest chain tip seen.";
        readonly labels: readonly [];
    };
    readonly ton_watch_max_lag_seconds: {
        readonly type: "gauge";
        readonly help: "Largest address lag: chain tip time minus the time the address was last known complete.";
        readonly labels: readonly [];
    };
    readonly ton_watch_gaps_open: {
        readonly type: "gauge";
        readonly help: "Missing ranges currently known, over all addresses.";
        readonly labels: readonly [];
    };
    readonly ton_watch_walks: {
        readonly type: "gauge";
        readonly help: "Missing ranges being fetched.";
        readonly labels: readonly [];
    };
    readonly ton_watch_walks_stuck: {
        readonly type: "gauge";
        readonly help: "Missing ranges waiting for a liteserver (archival) that can serve them.";
        readonly labels: readonly [];
    };
    readonly ton_watch_address_lag_seconds: {
        readonly type: "gauge";
        readonly help: "Chain tip time minus the time the address was last known complete; absent until known. Only with addressMetrics.";
        readonly labels: readonly ["address"];
    };
    readonly ton_watch_address_gaps_open: {
        readonly type: "gauge";
        readonly help: "Missing ranges currently known for the address. Only with addressMetrics.";
        readonly labels: readonly ["address"];
    };
    readonly ton_watch_walks_started_total: {
        readonly type: "counter";
        readonly help: "Walks (backward fetches over a missing range) started, by kind (head or gap).";
        readonly labels: readonly ["kind"];
    };
    readonly ton_watch_pages_total: {
        readonly type: "counter";
        readonly help: "Transaction pages fetched and stored, by walk kind (head or gap).";
        readonly labels: readonly ["kind"];
    };
    readonly ton_watch_tx_written_total: {
        readonly type: "counter";
        readonly help: "Transactions newly stored. Use rate() for throughput.";
        readonly labels: readonly [];
    };
    readonly ton_watch_splits_total: {
        readonly type: "counter";
        readonly help: "Long walks split into parallel pieces.";
        readonly labels: readonly [];
    };
    readonly ton_watch_split_points_total: {
        readonly type: "counter";
        readonly help: "Split points found for long walks.";
        readonly labels: readonly [];
    };
    readonly ton_watch_detect_fallbacks_total: {
        readonly type: "counter";
        readonly help: "Block listings that failed, so every address was polled instead.";
        readonly labels: readonly [];
    };
    readonly ton_watch_reconcile_misses_total: {
        readonly type: "counter";
        readonly help: "Transactions the block listing missed, found by reconciliation polling.";
        readonly labels: readonly [];
    };
    readonly ton_watch_history_pages_total: {
        readonly type: "counter";
        readonly help: "Pages served by the history plug-in, by plug-in name and reason (fallback or boost).";
        readonly labels: readonly ["source", "why"];
    };
    readonly ton_watch_source_calls_total: {
        readonly type: "counter";
        readonly help: "Calls to the chain, by method.";
        readonly labels: readonly ["method"];
    };
    readonly ton_watch_errors_total: {
        readonly type: "counter";
        readonly help: "Failures by kind (see ErrorKind) and where they happened.";
        readonly labels: readonly ["kind", "where"];
    };
    readonly ton_watch_consumer_delivered_total: {
        readonly type: "counter";
        readonly help: "Transactions handed to the consumer's handler and committed.";
        readonly labels: readonly ["consumer"];
    };
    readonly ton_watch_consumer_errors_total: {
        readonly type: "counter";
        readonly help: "Failed handler calls.";
        readonly labels: readonly ["consumer"];
    };
    readonly ton_watch_consumer_skipped_total: {
        readonly type: "counter";
        readonly help: 'Transactions given up on and skipped (onError "skip").';
        readonly labels: readonly ["consumer"];
    };
    readonly ton_watch_consumer_dead_letters_total: {
        readonly type: "counter";
        readonly help: 'Transactions given up on and dead-lettered (onError "dead-letter").';
        readonly labels: readonly ["consumer"];
    };
    readonly ton_watch_consumer_replayed_total: {
        readonly type: "counter";
        readonly help: "Dead letters replayed successfully.";
        readonly labels: readonly ["consumer"];
    };
    readonly ton_watch_consumer_lag_transactions: {
        readonly type: "gauge";
        readonly help: "Deliverable transactions the consumer has not delivered yet.";
        readonly labels: readonly ["consumer"];
    };
    readonly ton_watch_consumer_lag_seconds: {
        readonly type: "gauge";
        readonly help: "Age of the oldest deliverable transaction the consumer has not delivered yet.";
        readonly labels: readonly ["consumer"];
    };
    readonly ton_watch_consumer_watermark_lt: {
        readonly type: "gauge";
        readonly help: "Global order: lt the stream is released up to. A float64, exact below 2^53 (mainnet lt is near 2^46); use it for changes(), not for lt lookups.";
        readonly labels: readonly ["consumer"];
    };
};
export type MetricName = keyof typeof METRICS;
/** The label set a metric takes: exactly its declared labels. */
export type MetricLabels<N extends MetricName> = Record<(typeof METRICS)[N]["labels"][number], string>;
export type CounterName = {
    [N in MetricName]: (typeof METRICS)[N]["type"] extends "counter" ? N : never;
}[MetricName];
export type GaugeName = {
    [N in MetricName]: (typeof METRICS)[N]["type"] extends "gauge" ? N : never;
}[MetricName];
/** `value` if it is in `allowed`, else `"other"`: keeps a label's values a closed set. */
export declare function closedLabel<T extends string>(allowed: readonly T[], value: string): T;

// ---- source/history.d.ts
import type { TxId, TxRecord } from "../core/types";
/**
 * Optional plug-in that serves account history with bigger pages and deeper
 * retention than liteservers (e.g. `@ton/watch/toncenter`). The indexer only ever
 * asks it for the same thing it asks liteservers — "transactions of this address,
 * newest first, starting at this one" — and checks every page the same way, so a
 * history source can make fetching faster or reach further back, but cannot change
 * what gets stored.
 *
 * @experimental Methods may be added in minor 0.x versions. Exported from
 * `@ton/watch/advanced`.
 */
export interface HistorySource {
    readonly name: string;
    /** Largest page it serves (toncenter: up to 1000). */
    readonly maxPageSize: number;
    getTransactions(address: string, from: TxId, count: number): Promise<TxRecord[]>;
    /** True while it has no spare capacity (rate budget used up); `boost` mode then uses liteservers. */
    busy?(): boolean;
    close?(): Promise<void>;
}
export interface HistoryOptions {
    source: HistorySource;
    /**
     * - `fallback` (default): liteservers first; the history source only for ranges
     *   no liteserver serves any more (older than ~5 weeks on public servers).
     * - `boost`: also use it whenever it has spare capacity, for its bigger pages.
     */
    mode?: "fallback" | "boost";
    /** Off switch without removing the wiring. Default true. */
    enabled?: boolean;
}

// ---- source/liteserver/lite-source.d.ts
import { type ServerDefinition } from "@ton/ls";
import { LiteClient } from "ton-lite-client";
import type { TxId, TxRecord } from "../../core/types";
import { Metrics } from "../../metrics/metrics";
import type { ChainTip, TxSource } from "../source";
import { ServerPool, type ServerPoolOptions, type ServerStats } from "./server-pool";
export interface LiteSourceOptions extends ServerPoolOptions {
    /** Regular liteservers. Default: mainnet public config. */
    servers?: ServerDefinition;
    /** Archival liteservers, asked only for history the regular ones no longer have. */
    archiveServers?: ServerDefinition;
    /** How long to wait for the first connections. Default 10s. */
    connectTimeoutMs?: number;
    /** Blocks mode gives up (returns null → poll) when more shard blocks than this are pending. Default 400. */
    maxBlocksPerTick?: number;
    /** `findTxNear` gives up after looking at this many shard blocks. Default 128. */
    maxProbeBlocks?: number;
}
/**
 * The server pool of a `LiteSource`. Internal: for tests and benchmarks that make
 * raw liteserver calls through the same rotation; not part of the public API.
 */
export declare function serverPoolOf(source: LiteSource): ServerPool<LiteClient>;
/** Liteserver-backed `TxSource` with rotation, rate-limit backoff and archival fallback. */
export declare class LiteSource implements TxSource {
    readonly maxPageSize: number;
    readonly metrics: Metrics;
    private readonly pool;
    private readonly engines;
    private readonly maxBlocksPerTick;
    private readonly maxProbeBlocks;
    private lastTip;
    private firstTip;
    private constructor();
    /** Resolves the server lists, opens connections and waits for at least one. */
    static connect(options?: LiteSourceOptions): Promise<LiteSource>;
    /** Load, latency and errors of every liteserver, for status pages. */
    stats(): ServerStats[];
    getTip(): Promise<ChainTip>;
    getLastTx(address: string, tip: ChainTip): Promise<TxId | null>;
    getTransactions(address: string, from: TxId, count: number): Promise<TxRecord[]>;
    getTouchedAccounts(prev: ChainTip, next: ChainTip, workchains: ReadonlySet<number>): Promise<Map<string, TxId> | null>;
    findTxNear(address: string, lt: bigint, hint?: {
        ltPerTx?: number;
    }): Promise<TxId | null>;
    close(): Promise<void>;
    /**
     * Makes a lagging server wait for the newest block we know about instead of
     * answering "not found" for data it simply has not seen yet.
     */
    private awaitSeqno;
    /** Logical time a shard block spans, measured from consecutive tips. */
    private ltPerShardBlock;
    /**
     * Every block of the watched workchains after `prev` up to `next`: shard tops with
     * full ids, the blocks between them by seqno only. Null when the shard layout
     * changed (split/merge) or there are too many to list.
     */
    private blocksBetween;
    private lookupBlock;
    /** Every transaction id in a block, following `incomplete` pages. */
    private listBlockTransactions;
    /** The account's newest transaction in one shard block, if it has any there. */
    private lastTxOfAccountInBlock;
}

// ---- source/liteserver/server-pool.d.ts
import { type ErrorKind } from "../../core/errors";
import { Metrics } from "../../metrics/metrics";
import { type Logger } from "../../util/logger";
/** One server a `ServerPool` can send calls to. */
export interface PoolMember<C> {
    id: string;
    client: C;
    /** Archival servers are only asked after a regular one could not serve the data. */
    archive?: boolean;
    isReady?: () => boolean;
}
export interface ServerPoolOptions {
    /** Requests in flight per server. Default 4. */
    maxInFlightPerServer?: number;
    /** Per-request timeout. Default 10s. */
    timeoutMs?: number;
    /** Failed attempts (other than archive misses) before giving up on a call. Default 6. */
    maxAttempts?: number;
    /** Cap for the per-server cooldown after rate limits and failures. Default 30s. */
    maxCooldownMs?: number;
    metrics?: Metrics;
    logger?: Logger;
}
/** A pool member with its live load and health bookkeeping. */
export interface ServerState<C> extends PoolMember<C> {
    inFlight: number;
    cooldownUntil: number;
    /** Consecutive rate-limit responses. */
    rateLimits: number;
    /** Consecutive timeouts / network errors / not-ready answers. */
    failures: number;
    /** Smoothed response time. */
    latencyMs: number;
    calls: number;
    errors: Partial<Record<ErrorKind, number>>;
}
/** Point-in-time view of one server, for status pages. */
export interface ServerStats {
    id: string;
    archive: boolean;
    ready: boolean;
    inFlight: number;
    latencyMs: number;
    calls: number;
    coolingDownMs: number;
    errors: Partial<Record<ErrorKind, number>>;
}
/**
 * Spreads calls over a set of servers: least-loaded/fastest first, a bounded number
 * of requests per server, and per-kind error handling:
 *
 * - `rate_limit`: the server cools down (exponential, capped) and the call moves on.
 * - `timeout`/`network`: short cooldown, retry elsewhere.
 * - `archive_unavailable`/`bad_response`: that server is skipped for this call; once
 *   every regular server has failed, archival servers are tried.
 */
export declare class ServerPool<C> {
    readonly members: ServerState<C>[];
    readonly metrics: Metrics;
    private readonly maxInFlight;
    private readonly timeoutMs;
    private readonly maxAttempts;
    private readonly maxCooldownMs;
    private readonly logger;
    private slotWaiters;
    constructor(members: PoolMember<C>[], options?: ServerPoolOptions);
    /** Requests the regular (non-archival) servers can have in flight at once. */
    get capacity(): number;
    stats(): ServerStats[];
    /**
     * Runs `fn` against the best available server, moving to another one on failure
     * according to the error kind. Throws a `SourceError` once no server can serve it.
     */
    call<T>(method: string, fn: (client: C) => Promise<T>): Promise<T>;
    private coolDown;
    private exhaustedError;
    private withTimeout;
    private wakeSlotWaiters;
    /**
     * Picks the best available server, waiting while all candidates are busy or
     * cooling down. Returns null when every server has been ruled out for this call.
     */
    private acquire;
    /** Connected regular servers not ruled out; archival ones only when none is left. */
    private candidates;
    private waitForSlot;
}

// ---- source/source.d.ts
import type { TxId, TxRecord } from "../core/types";
import type { Metrics } from "../metrics/metrics";
/** Full identifier of a block. */
export interface BlockRef {
    workchain: number;
    /** Shard id as a signed 64-bit decimal string. */
    shard: string;
    seqno: number;
    rootHash: Buffer;
    fileHash: Buffer;
}
/** The newest block of one shard as of a masterchain block. */
export interface ShardTop extends BlockRef {
    /** Logical time at the end of the block. */
    endLt: bigint;
}
/** A masterchain block the indexer works against. */
export interface ChainTip {
    seqno: number;
    utime: number;
    block: BlockRef;
    /** Top block of every shard as of this masterchain block. */
    shards: ShardTop[];
    /**
     * Every transaction with `lt <= syncLt`, of any account, is final and visible at
     * this block (min `end_lt` over the shard tops). An address whose last
     * transaction at this block is already stored is complete up to `syncLt`.
     */
    syncLt: bigint;
}
/**
 * Where transactions come from. `LiteSource` is the liteserver implementation; tests
 * use a fake. Every method may throw a `SourceError`.
 *
 * @experimental Custom implementations are unsupported in 0.x: methods may be
 * added in minor versions. Exported from `@ton/watch/advanced`.
 */
export interface TxSource {
    getTip(): Promise<ChainTip>;
    /** Last transaction of `address` as of `tip`, or null if it has none. */
    getLastTx(address: string, tip: ChainTip): Promise<TxId | null>;
    /**
     * Up to `count` transactions of `address`, newest first, starting at `from`
     * (inclusive) and walking back through prev links.
     */
    getTransactions(address: string, from: TxId, count: number): Promise<TxRecord[]>;
    /**
     * Accounts that had transactions in blocks after `prev` up to `next`, with their
     * newest transaction. Returns null when it cannot tell (shard split/merge, too
     * far behind); the caller then falls back to polling every address.
     */
    getTouchedAccounts?(prev: ChainTip, next: ChainTip, workchains: ReadonlySet<number>): Promise<Map<string, TxId> | null>;
    /**
     * Optional: some transaction of `address` with lt at or below `lt`, close to it.
     * Lets the indexer cut one long missing range into pieces fetched in parallel
     * (a single range is otherwise a strictly sequential walk, one page per round
     * trip). Returns null when nothing is found cheaply.
     */
    findTxNear?(address: string, lt: bigint, hint?: {
        ltPerTx?: number;
    }): Promise<TxId | null>;
    /** Largest `count` that `getTransactions` honors. */
    readonly maxPageSize: number;
    /** When set, the indexer records into the same registry. */
    readonly metrics?: Metrics;
    close?(): Promise<void>;
}

// ---- stores/consumer-state.d.ts
import type { AddressInput } from "../core/address";
/** Delivery order of a consumer (see `ProcessOptions.order`). */
export type ConsumerOrder = "address" | "global";
/** A consumer's position on one address, with the failure state of the transaction after it. */
export interface CursorState {
    consumer: string;
    /** Lowercase raw address. */
    address: string;
    /** Lt of the last transaction delivered, skipped or dead-lettered. */
    lt: bigint;
    /** When the cursor last moved: the last delivery, skip, dead letter or rewind. */
    updatedAt: Date;
    /** Failed handler attempts on the transaction after the cursor; 0 when it has not failed. */
    attempts: number;
    lastError: string | null;
    firstFailureAt: Date | null;
    lastFailureAt: Date | null;
}
/** A consumer known to the store. */
export interface ConsumerRecord {
    name: string;
    /** Order it last ran with; null for a consumer whose cursors predate the record. */
    order: ConsumerOrder | null;
    /** When it first ran; null when unknown (see `order`). */
    createdAt: Date | null;
    cursors: CursorState[];
}
/** A transaction a consumer gave up on after `maxAttempts` failed handler calls. */
export interface DeadLetter {
    consumer: string;
    /** Lowercase raw address. */
    address: string;
    lt: bigint;
    hash: Buffer;
    /** Message of the last error. */
    error: string;
    attempts: number;
    firstFailureAt: Date;
    lastFailureAt: Date;
}
export interface DeadLetterFilter {
    consumer?: string;
    address?: AddressInput;
    lt?: bigint;
    /** Default: no limit. */
    limit?: number;
}
/** A `DeadLetterFilter` whose address is already normalized (store internals). */
export type RawDeadLetterFilter = Omit<DeadLetterFilter, "address"> & {
    address?: string;
};
/**
 * Stored, not yet delivered transactions of one address for one consumer.
 *
 * @experimental Part of the `Store` contract; custom stores are unsupported in 0.x.
 */
export interface Backlog {
    address: string;
    cursor: bigint;
    /** Stored transactions above the cursor, up to the frontier (and `uptoLt`). */
    transactions: number;
    /** Lt of the newest of them; null when there are none. */
    newestLt: bigint | null;
    /** Chain time of the oldest of them; null when there are none. */
    oldestUtime: number | null;
}
/**
 * A consumer's single-instance lock, held until released (or its connection is lost).
 *
 * @experimental Part of the `Store` contract; custom stores are unsupported in 0.x.
 */
export interface ConsumerLock {
    /** False once released or once the connection holding it broke. */
    readonly held: boolean;
    release(): Promise<void>;
}
/**
 * The per-consumer half of a `Store`: delivery positions, failure counts, dead
 * letters and the single-instance lock. Addresses are normalized as `Store` describes.
 *
 * @experimental Custom implementations are unsupported in 0.x: methods may be
 * added in minor versions.
 */
export interface ConsumerStateStore {
    getCursor(consumer: string, address: string): Promise<bigint | null>;
    /** Moves the cursor (either direction) and clears its failure state. */
    setCursor(consumer: string, address: string, lt: bigint): Promise<void>;
    /**
     * Moves the cursor to `lt` and clears its failure state, but only if it still is
     * at `expected` (`null`: only if there is no cursor yet). Resolves to false,
     * changing nothing, if another writer moved it. Inside `Store.transaction` a
     * concurrent move commits first or waits for this one, never both.
     */
    compareAndSetCursor(consumer: string, address: string, expected: bigint | null, lt: bigint): Promise<boolean>;
    /** Cursors of active and inactive addresses, of one consumer or all of them. */
    listCursors(consumer?: string): Promise<CursorState[]>;
    /**
     * Counts a failed attempt on the transaction after the cursor. Resolves to the
     * updated cursor, or null if the consumer has no cursor on the address.
     */
    recordFailure(consumer: string, address: string, error: string): Promise<CursorState | null>;
    /** Records that a consumer runs (with this order). Idempotent. */
    saveConsumer(name: string, order: ConsumerOrder): Promise<void>;
    /** Every consumer with a record or a cursor, by name. */
    listConsumers(): Promise<ConsumerRecord[]>;
    /** Deletes a consumer's record, cursors and dead letters. */
    deleteConsumer(name: string): Promise<void>;
    /** Inserts a dead letter, or replaces the one for the same (consumer, address, lt). */
    putDeadLetter(letter: DeadLetter): Promise<void>;
    /**
     * Replaces the dead letter for the same (consumer, address, lt) only if it still
     * exists; resolves to false, inserting nothing, if it does not.
     */
    updateDeadLetter(letter: DeadLetter): Promise<boolean>;
    /** Oldest first (by consumer, address, lt). */
    listDeadLetters(filter?: DeadLetterFilter): Promise<DeadLetter[]>;
    /** Resolves to false if there was no such dead letter. */
    deleteDeadLetter(consumer: string, address: string, lt: bigint): Promise<boolean>;
    /**
     * Per active address the consumer has a cursor on: what is stored above the cursor
     * up to the address's frontier, and up to `uptoLt` if given.
     */
    backlog(consumer: string, uptoLt?: bigint): Promise<Backlog[]>;
    /**
     * Optional: takes the lock that keeps a consumer name running in one place at a
     * time. Resolves to null if another instance holds it. Without this method
     * nothing stops two instances from delivering the same transactions.
     */
    lockConsumer?(name: string): Promise<ConsumerLock | null>;
}

// ---- stores/memory/memory-store.d.ts
import type { AddressState, Gap, TxId, TxRecord } from "../../core/types";
import type { Backlog, ConsumerLock, ConsumerOrder, ConsumerRecord, CursorState, DeadLetter, DeadLetterFilter } from "../consumer-state";
import type { AddAddressOptions, Store } from "../store";
/** In-process store. Useful for tests, benchmarks, and short-lived tools. */
export declare class MemoryStore implements Store {
    private readonly entries;
    private readonly consumerState;
    migrate(): Promise<void>;
    close(): Promise<void>;
    addAddress(input: string, options: AddAddressOptions): Promise<void>;
    removeAddress(input: string, options?: {
        purge?: boolean;
    }): Promise<void>;
    getAddress(address: string): Promise<AddressState | null>;
    listAddresses(options?: {
        includeInactive?: boolean;
    }): Promise<AddressState[]>;
    write(address: string, txs: TxRecord[]): Promise<number>;
    findGaps(address: string, limit?: number): Promise<Gap[]>;
    advanceFrontier(address: string): Promise<TxId | null>;
    markSynced(addresses: string[], syncLt: bigint, utime: number): Promise<void>;
    read(address: string, afterLt: bigint, uptoLt: bigint, limit: number): Promise<TxRecord[]>;
    getCursor(consumer: string, address: string): Promise<bigint | null>;
    setCursor(consumer: string, address: string, lt: bigint): Promise<void>;
    compareAndSetCursor(consumer: string, address: string, expected: bigint | null, lt: bigint): Promise<boolean>;
    listCursors(consumer?: string): Promise<CursorState[]>;
    recordFailure(consumer: string, address: string, error: string): Promise<CursorState | null>;
    saveConsumer(name: string, order: ConsumerOrder): Promise<void>;
    listConsumers(): Promise<ConsumerRecord[]>;
    deleteConsumer(name: string): Promise<void>;
    putDeadLetter(letter: DeadLetter): Promise<void>;
    updateDeadLetter(letter: DeadLetter): Promise<boolean>;
    listDeadLetters(filter?: DeadLetterFilter): Promise<DeadLetter[]>;
    deleteDeadLetter(consumer: string, address: string, lt: bigint): Promise<boolean>;
    backlog(consumer: string, uptoLt?: bigint): Promise<Backlog[]>;
    /** In-process only: another `Consumer` of the same name on this store is refused. */
    lockConsumer(name: string): Promise<ConsumerLock | null>;
    /** Number of stored transactions (all addresses). */
    get size(): number;
    /** The entry of a tracked address; throws `UNKNOWN_ADDRESS` for any other. */
    private entry;
    private sorted;
    private snapshot;
    /** Frontier and gaps above the stored frontier. */
    private analyze;
}

// ---- stores/pg/database.d.ts
import type { Pool } from "pg";
/**
 * Anything that can run a parameterized query: `pg.Pool`, `pg.PoolClient`, PGlite.
 * What consumer handlers get as `ctx.db` with `PgStore`.
 */
export interface PgQueryable {
    query(text: string, params?: unknown[]): Promise<{
        rows: unknown[];
    }>;
}
/**
 * One dedicated database connection, kept until `release()`. Session state such
 * as advisory locks lives on it.
 */
export interface PgSession extends PgQueryable {
    /** Returns the connection; `destroy` closes it instead of reusing it. */
    release(destroy?: boolean): void;
    /** Registers a callback for when the connection breaks (its session state is gone). */
    onClose(listener: () => void): void;
}
/** A queryable that can also run a callback inside a transaction (PGlite has this natively). */
export interface PgDatabase extends PgQueryable {
    transaction<T>(fn: (tx: PgQueryable) => Promise<T>): Promise<T>;
    /**
     * Optional: opens a dedicated connection. Without it the database is treated as
     * a single session, as PGlite is.
     */
    session?(): Promise<PgSession>;
}
/**
 * Adapts a `pg.Pool` to `PgDatabase`. A `session()` keeps one pool client for
 * itself, so it is refused when it would leave the pool no client for queries:
 * with `pg`'s default `connectionTimeoutMillis` of 0 those would wait forever.
 */
export declare function poolDatabase(pool: Pool): PgDatabase;

// ---- stores/pg/migrations.d.ts
/** Replaced with the quoted schema name in every statement. */
export declare const SCHEMA_PLACEHOLDER = "$S";
export interface Migration {
    /** Position in the history: 1, 2, 3, … with no gaps. */
    version: number;
    /** snake_case, unique. */
    name: string;
    /** One statement per string, every table reference written as `$S.<table>`. */
    up: readonly string[];
    /**
     * Default true: all statements and the bookkeeping row commit atomically.
     * `false` runs them one by one outside a transaction, as `create index concurrently`
     * requires. A crash can then leave the migration half applied, so every statement
     * must be safe to run again (`if not exists`); an index left INVALID by a crashed
     * concurrent build is dropped and rebuilt on the next run.
     */
    transaction?: boolean;
    /**
     * Oldest schema version whose code keeps working once this migration is applied:
     * code that knows only migrations up to that version may still run against the
     * database (e.g. old instances during a rolling deploy). Default: this migration's
     * own version, i.e. older code refuses to start. Set it only for expand-only
     * changes that older code is known to tolerate (see docs/migrations.md).
     */
    compatibleFrom?: number;
}
/**
 * The schema history, applied in order and recorded in `<schema>.schema_migrations`.
 * Released migrations are frozen (tests/fixtures/migrations pins each one's checksum):
 * append a new one, never edit or remove one. Rules: docs/migrations.md.
 */
export declare const migrations: readonly Migration[];
/**
 * sha256 of a migration's statements, insensitive to whitespace (re-indenting the
 * source is not an edit). Stored per applied migration and checked on every migrate.
 */
export declare function migrationChecksum(migration: Pick<Migration, "up">): string;
/** The oldest code version `migration` tolerates (see `Migration.compatibleFrom`). */
export declare function compatibleFrom(migration: Migration): number;

// ---- stores/pg/migrator.d.ts
import { TonWatchError } from "../../core/errors";
import type { PgDatabase } from "./database";
import { type Migration } from "./migrations";
/**
 * Why `migrate()` refused to touch a schema:
 * - `MIGRATION_MODIFIED`: an applied migration's statements differ from this code's
 *   (it was edited).
 * - `MIGRATION_TOO_NEW`: a newer ton-watch applied migrations this code does not know
 *   and marked at least one of them incompatible with it. Upgrade ton-watch.
 * - `MIGRATION_DIVERGED`: the recorded history cannot be reconciled with this code's
 *   (a pre-release schema, an unknown or missing version below the newest applied one).
 */
export type MigrationErrorCode = "MIGRATION_MODIFIED" | "MIGRATION_TOO_NEW" | "MIGRATION_DIVERGED";
/** `migrate()` refused a schema and changed nothing; see `MigrationErrorCode`. */
export declare class MigrationError extends TonWatchError<MigrationErrorCode> {
    name: string;
}
/** What one `migrateSchema` call did. */
export interface MigrationResult {
    /** Versions applied by this call, ascending. */
    applied: number[];
    /** Applied versions newer than this code knows (all compatible with it), ascending. */
    newer: number[];
}
/**
 * `create [unique] index concurrently if not exists <name> on …`, the one accepted
 * form of a concurrent index build (`<name>` unquoted, lowercase).
 */
export declare const CONCURRENT_INDEX: RegExp;
/**
 * Creates `schema` if missing and applies the pending ones of `list` (default: the
 * real history). Any number of processes may call it at once: everything runs under
 * the advisory lock `hashtext('ton_watch:<schema>')`. Fails with `MigrationError`,
 * before changing anything, when the recorded history does not match `list`.
 *
 * Transactional migrations run in one transaction holding the lock, which needs no
 * dedicated connection. A non-transactional one (`transaction: false`) needs the
 * lock across several transactions, so from there on everything runs on a dedicated
 * session (`db.session()`) holding the session-level lock.
 *
 * The lock is polled with the `try` variants rather than waited for: a waiter
 * blocked inside a statement keeps a snapshot open, and a `create index
 * concurrently` run by the holder waits for every such snapshot — a deadlock.
 */
export declare function migrateSchema(db: PgDatabase, schema: string, list?: readonly Migration[]): Promise<MigrationResult>;

// ---- stores/pg/pg-store.d.ts
import type { Pool } from "pg";
import type { AddressState, Gap, TxId, TxRecord } from "../../core/types";
import type { Backlog, ConsumerLock, ConsumerOrder, ConsumerRecord, CursorState, DeadLetter, DeadLetterFilter } from "../consumer-state";
import type { AddAddressOptions, Store, StoreTransaction } from "../store";
import { type PgDatabase, type PgQueryable } from "./database";
export interface PgStoreOptions {
    /** Postgres schema holding the tables. Created if missing. Default `ton_watch`. */
    schema?: string;
    /** Called by `close()`, e.g. `() => pool.end()`. Not called by default: the pool is yours. */
    onClose?: () => Promise<void>;
}
/**
 * Postgres store, the reference implementation. Works with a `pg` `Pool` and with
 * PGlite (or anything else shaped like `PgDatabase`).
 *
 * Consumer handlers receive the open transaction as `ctx.db` (a `PgQueryable`):
 * write your own effects through it and they commit together with the cursor.
 */
export declare class PgStore implements Store<PgQueryable> {
    /** Postgres schema holding the tables. */
    readonly schema: string;
    private readonly db;
    private readonly quotedSchema;
    private readonly onClose?;
    private readonly consumerState;
    constructor(db: Pool | PgDatabase, options?: PgStoreOptions);
    /**
     * Creates the schema and applies pending migrations. Safe to run from several
     * processes at once. Throws `MigrationError` instead of touching a schema whose
     * history does not match this version's: an edited migration, or a schema
     * migrated by a newer ton-watch that marked its changes incompatible with this one.
     */
    migrate(): Promise<void>;
    close(): Promise<void>;
    addAddress(address: string, options: AddAddressOptions): Promise<void>;
    removeAddress(address: string, options?: {
        purge?: boolean;
    }): Promise<void>;
    getAddress(address: string): Promise<AddressState | null>;
    listAddresses(options?: {
        includeInactive?: boolean;
    }): Promise<AddressState[]>;
    write(address: string, txs: TxRecord[]): Promise<number>;
    findGaps(address: string, limit?: number): Promise<Gap[]>;
    advanceFrontier(address: string): Promise<TxId | null>;
    markSynced(addresses: string[], syncLt: bigint, utime: number): Promise<void>;
    read(address: string, afterLt: bigint, uptoLt: bigint, limit: number): Promise<TxRecord[]>;
    getCursor(consumer: string, address: string): Promise<bigint | null>;
    setCursor(consumer: string, address: string, lt: bigint): Promise<void>;
    compareAndSetCursor(consumer: string, address: string, expected: bigint | null, lt: bigint): Promise<boolean>;
    listCursors(consumer?: string): Promise<CursorState[]>;
    recordFailure(consumer: string, address: string, error: string): Promise<CursorState | null>;
    saveConsumer(name: string, order: ConsumerOrder): Promise<void>;
    listConsumers(): Promise<ConsumerRecord[]>;
    deleteConsumer(name: string): Promise<void>;
    putDeadLetter(letter: DeadLetter): Promise<void>;
    updateDeadLetter(letter: DeadLetter): Promise<boolean>;
    listDeadLetters(filter?: DeadLetterFilter): Promise<DeadLetter[]>;
    deleteDeadLetter(consumer: string, address: string, lt: bigint): Promise<boolean>;
    backlog(consumer: string, uptoLt?: bigint): Promise<Backlog[]>;
    /**
     * Session-level advisory lock keyed on (schema, consumer name), held on a
     * dedicated connection (one pool client per running consumer) until released.
     */
    lockConsumer(name: string): Promise<ConsumerLock | null>;
    transaction<T>(fn: (tx: StoreTransaction<PgQueryable>) => Promise<T>): Promise<T>;
    /** Runs `sql` with `$S` replaced by the schema; rows are typed by the caller. */
    private query;
}

// ---- stores/store.d.ts
import type { AddressState, Gap, TxId, TxRecord } from "../core/types";
import type { ConsumerStateStore } from "./consumer-state";
/**
 * How a store starts tracking an address.
 *
 * @experimental Custom store implementations are unsupported in 0.x.
 */
export interface AddAddressOptions {
    /** Transactions with `lt <= startLt` are out of scope. 0 = full history. */
    startLt: bigint;
    /** Known-complete chain lt at the time of adding (e.g. when starting "from now"). */
    syncedLt?: bigint;
    /** Chain unix time of `syncedLt`. */
    syncedUtime?: number;
}
/**
 * Handed to the callback of `Store.transaction`.
 *
 * @experimental Custom store implementations are unsupported in 0.x.
 */
export interface StoreTransaction<Db = unknown> {
    /** The same store, bound to the open database transaction. */
    store: Store<Db>;
    /**
     * The store's native transaction handle, handed to consumer handlers as
     * `HandlerContext.db` (for `PgStore`, a `PgQueryable` on the open transaction).
     */
    db: Db;
}
/**
 * Storage for the indexer. Writes are idempotent and may arrive in any order and
 * concurrently; completeness is derived from the prev links, so a store never needs
 * to know which fetch produced a transaction. `PgStore` is the reference
 * implementation, `MemoryStore` the minimal one.
 *
 * Consumer positions, failures and dead letters are the `ConsumerStateStore` half.
 *
 * Addresses: implementations accept any form `toRawAddress` does and normalize
 * with it before using an address as a key, so `0:ABC…` and `0:abc…` are one
 * address; every address they return is lowercase raw.
 *
 * `Db` is the native transaction handle of `transaction()`, which consumer
 * handlers receive as `HandlerContext.db`.
 *
 * @experimental Custom implementations are unsupported in 0.x: methods may be
 * added in minor versions. Use `PgStore` or `MemoryStore`.
 */
export interface Store<Db = unknown> extends ConsumerStateStore {
    /** Creates/upgrades the schema. Idempotent. Never drops data. */
    migrate(): Promise<void>;
    close(): Promise<void>;
    /** Starts tracking an address. Re-activates it if it was removed; never changes its startLt. */
    addAddress(address: string, options: AddAddressOptions): Promise<void>;
    /** Stops tracking. With `purge`, also deletes its transactions, cursors and dead letters. */
    removeAddress(address: string, options?: {
        purge?: boolean;
    }): Promise<void>;
    getAddress(address: string): Promise<AddressState | null>;
    listAddresses(options?: {
        includeInactive?: boolean;
    }): Promise<AddressState[]>;
    /**
     * Inserts transactions of one address, ignoring ones already stored and ones at or
     * below its startLt. Returns how many were new.
     */
    write(address: string, txs: TxRecord[]): Promise<number>;
    /** Missing ranges above the frontier, oldest first. */
    findGaps(address: string, limit?: number): Promise<Gap[]>;
    /** Recomputes and persists the frontier (it only ever moves forward). */
    advanceFrontier(address: string): Promise<TxId | null>;
    /**
     * Records that, as of a chain block with `syncLt`, the address had no transactions
     * beyond what is stored. Applied only to addresses whose frontier equals their
     * head, i.e. nothing is missing.
     */
    markSynced(addresses: string[], syncLt: bigint, utime: number): Promise<void>;
    /** Transactions with `afterLt < lt <= uptoLt`, ascending. */
    read(address: string, afterLt: bigint, uptoLt: bigint, limit: number): Promise<TxRecord[]>;
    /**
     * Optional: runs `fn` atomically. Consumers use it to commit the handler's own
     * writes (through `db`) together with the cursor, giving exactly-once effects.
     */
    transaction?<T>(fn: (tx: StoreTransaction<Db>) => Promise<T>): Promise<T>;
}
/** Runs `fn` in a store transaction if the store has them, otherwise directly. */
export declare function runAtomically<T, Db>(store: Store<Db>, fn: (store: Store<Db>) => Promise<T>): Promise<T>;

// ---- ton-watch.d.ts
import { EventEmitter } from "node:events";
import { Consumer } from "./consumer/consumer";
import type { ConsumerLag, ProcessOptions, RewindOptions, RewindTarget, TxHandler } from "./consumer/types";
import { type AddressInput } from "./core/address";
import { type AddressState } from "./core/types";
import type { IndexerEventMap } from "./indexer/events";
import type { IndexingOptions } from "./indexer/options";
import type { AddressStatus } from "./indexer/status";
import { Metrics } from "./metrics/metrics";
import type { TxSource } from "./source/source";
import type { ConsumerRecord, DeadLetter, DeadLetterFilter } from "./stores/consumer-state";
import type { Store } from "./stores/store";
import { type Logger } from "./util/logger";
export interface TonWatchOptions<Db = unknown> extends IndexingOptions {
    /**
     * Where transactions, addresses and consumer positions live. `TonWatch` takes
     * ownership: `close()` closes it. Its type decides `HandlerContext.db`
     * (`PgQueryable` with `PgStore`).
     */
    store: Store<Db>;
    /** Where transactions come from. `TonWatch` takes ownership: `close()` closes it. */
    source: TxSource;
    /** Run migrations on start. Default true. */
    migrate?: boolean;
    /** Default: the source's metrics, or a new registry. */
    metrics?: Metrics;
    /** Default: a console logger at level `info`. */
    logger?: Logger;
}
export interface AddAddressOptions {
    /**
     * What history to index:
     * - `"now"` (default): only transactions after this moment.
     * - `"earliest"`: the account's full history.
     * - an lt: transactions with a greater lt.
     */
    from?: "now" | "earliest" | bigint;
}
export interface RemoveAddressOptions {
    /** Also delete the address's transactions and every consumer's cursor on it. */
    purge?: boolean;
}
export interface HealthOptions {
    /** Lag beyond which an address makes the health `degraded`. Default 120. */
    maxLagSeconds?: number;
}
/** Events emitted by `TonWatch`, with their listener arguments (forwarded from indexing). */
export type TonWatchEventMap = IndexerEventMap;
/** Service health, as served on `/health`. */
export interface Health {
    /** `down`: not running or not ticking; `degraded`: running with problems (see `reasons`). */
    status: "ok" | "degraded" | "down";
    running: boolean;
    tip: {
        seqno: number;
        utime: number;
        ageSeconds: number;
    } | null;
    addresses: number;
    maxLagSeconds: number | null;
    gapsOpen: number;
    stuckRanges: number;
    txWrittenPerSecond: number;
    reasons: string[];
}
/**
 * Indexes the transactions of a set of addresses and hands them to consumers in
 * chain order. Fetching runs in any order and in parallel; ordering is enforced
 * only when reading.
 *
 * Owns its `store` and `source`: `stop()` pauses and can be followed by
 * `start()`, `close()` stops for good and closes both.
 *
 * Emits `tick`, `frontier`, `synced` and `fetchError` (see `TonWatchEventMap`).
 */
export declare class TonWatch<Db = unknown> extends EventEmitter<TonWatchEventMap> {
    readonly store: Store<Db>;
    readonly source: TxSource;
    readonly metrics: Metrics;
    private readonly indexer;
    private readonly logger;
    private readonly registered;
    private readonly shouldMigrate;
    private started;
    private migrated;
    private closed;
    constructor(options: TonWatchOptions<Db>);
    /** Runs migrations (never drops anything). Called by `start()`. */
    init(): Promise<void>;
    /**
     * Starts every consumer registered with `process()`, then indexing. Rejects with
     * `ConsumerLockedError` (and starts nothing) if a consumer runs elsewhere.
     */
    start(): Promise<void>;
    /**
     * Graceful stop: consumers finish their current transaction, in-flight fetches
     * complete. Store and source stay open; `start()` resumes.
     */
    stop(): Promise<void>;
    /**
     * `stop()`, then closes the source and the store. Final: afterwards `start()`,
     * `init()` and `addAddress()` reject with code `CLOSED`. Calling it again
     * returns the same promise.
     */
    close(): Promise<void>;
    private assertOpen;
    /**
     * Starts tracking an address (friendly or raw, or an `Address`). Resolves to its
     * raw form, the one every output uses.
     */
    addAddress(address: AddressInput, options?: AddAddressOptions): Promise<string>;
    /** Stops tracking an address; with `purge`, also deletes its transactions and cursors. */
    removeAddress(address: AddressInput, options?: RemoveAddressOptions): Promise<void>;
    addresses(): Promise<AddressState[]>;
    /**
     * Delivers transactions to `handler` in chain order. `name` identifies the
     * consumer's stored position: reuse it to resume, change it to start over.
     * One instance per name delivers at a time (see `ProcessOptions.lock`); when
     * registered after `start()`, await `consumer.ready()` to learn if it got the lock.
     * Throws code `CONSUMER_REGISTERED` if `name` is already registered here.
     */
    process(name: string, handler: TxHandler<Db>, options?: ProcessOptions): Consumer<Db>;
    private consumerNamed;
    /** Every consumer the store knows (also ones run by other processes), with its cursors. */
    consumers(): Promise<ConsumerRecord[]>;
    /**
     * How far a consumer is behind (see `ConsumerLag`); it need not run in this
     * process. Rejects with code `UNKNOWN_CONSUMER` if the store does not know it.
     */
    consumerLag(name: string): Promise<ConsumerLag>;
    /**
     * Moves a consumer's cursors to `to`: `"earliest"` (redeliver everything), `"now"`
     * (skip to each frontier) or an lt (deliver what comes after it). A consumer
     * registered here applies it between rounds; one running in another process
     * makes this reject with `ConsumerLockedError`.
     */
    rewindConsumer(name: string, to: RewindTarget, options?: RewindOptions): Promise<void>;
    /**
     * Deletes a consumer's record, cursors and dead letters; it starts over under the
     * same name. Rejects with `ConsumerLockedError` while it runs anywhere, and with
     * code `CONSUMER_REGISTERED` if it is registered in this process.
     */
    deleteConsumer(name: string): Promise<void>;
    /** Dead letters of every consumer, or as filtered; oldest first. */
    deadLetters(filter?: DeadLetterFilter): Promise<DeadLetter[]>;
    /** Deletes a dead letter without redelivering it. False if there was none. */
    discardDeadLetter(consumer: string, address: AddressInput, lt: bigint): Promise<boolean>;
    /**
     * Redelivers a dead letter through a consumer registered here (see
     * `Consumer.replayDeadLetter`). Rejects with code `UNKNOWN_CONSUMER` if none is.
     */
    replayDeadLetter(consumer: string, address: AddressInput, lt: bigint): Promise<void>;
    /**
     * The lowest complete-up-to lt across `addresses` (default: all): every
     * transaction of these addresses with a lower or equal lt is stored.
     */
    watermark(addresses?: readonly AddressInput[]): Promise<bigint | null>;
    /** Indexing state of every tracked address, as of the last tick. */
    status(): AddressStatus[];
    /** Overall indexing health, as of the last tick (see `Health`). */
    health(options?: HealthOptions): Health;
}

// ---- util/logger.d.ts
/** Minimal logging interface; `console` satisfies it, as do most logging libraries. */
export interface Logger {
    debug(...args: unknown[]): void;
    info(...args: unknown[]): void;
    warn(...args: unknown[]): void;
    error(...args: unknown[]): void;
}
declare const LOG_LEVELS: readonly ["debug", "info", "warn", "error", "silent"];
/** Lowest level a `consoleLogger` prints; `silent` prints nothing. */
export type LogLevel = (typeof LOG_LEVELS)[number];
/** Whether a string names a log level. */
export declare function isLogLevel(value: string): value is LogLevel;
/** Logs to the console with a `[ton-watch]` prefix, dropping messages below `level`. */
export declare function consoleLogger(level?: LogLevel): Logger;
/** Discards everything. The default for library components. */
export declare const silentLogger: Logger;
export {};
