// API snapshot of parse/index.d.ts; generated by tests/api-snapshot.test.ts (UPDATE_API_SNAPSHOT=1).

// ---- parse/index.d.ts
/**
 * Typed transaction parsing: outcome and bounce flags, decoded comments, TEP-74
 * jetton and TEP-62 NFT messages, and deposit checks. Depends only on
 * `@ton/core`; usable on any `Transaction`, not just ones from the indexer.
 *
 * @module
 */
export { type ParseBodyOptions, parseMessageBody } from "./body";
export { type IncomingJettonTransfer, type IncomingJettonTransferOptions, type IncomingPayment, incomingJettonTransfer, incomingPayment, type JettonWallets, } from "./deposits";
export { parseMessage } from "./message";
export { Op } from "./opcodes";
export { type ParseTransactionOptions, parseTransaction, type TransactionInput, } from "./transaction";
export type * from "./types";

// ---- core/types.d.ts
import { type Transaction } from "@ton/core";
/** Identifies one transaction of an account: logical time + cell hash. */
export interface TxId {
    lt: bigint;
    hash: Buffer;
}
/**
 * A transaction as the indexer stores it. Every account transaction links to the
 * previous one through `prevLt`/`prevHash`; that link is what lets writes land in
 * any order and still be checked for completeness. `prevLt === 0n` marks the
 * account's very first transaction.
 */
export interface TxRecord {
    /** Raw address, `<workchain>:<hex>`. */
    address: string;
    lt: bigint;
    hash: Buffer;
    prevLt: bigint;
    prevHash: Buffer;
    /** Unix time of the block the transaction is in. */
    utime: number;
    /** The transaction cell serialized as a BOC. */
    boc: Buffer;
}
/** What the store knows about one tracked address. */
export interface AddressState {
    /** Raw address, `<workchain>:<hex>`. */
    address: string;
    /** Transactions with `lt <= startLt` are out of scope and never fetched or delivered. */
    startLt: bigint;
    active: boolean;
    /** Newest stored transaction. */
    head: TxId | null;
    /**
     * Newest transaction such that every transaction between `startLt` and it is
     * stored. Ordered delivery never goes past this point.
     */
    frontier: TxId | null;
    /**
     * Chain logical time up to which the address is known complete, even when it
     * had no transactions: no transaction with `lt <= syncedLt` is missing.
     * Used for the cross-address watermark.
     */
    syncedLt: bigint;
    /** Chain unix time at which `syncedLt` was observed, for lag reporting. */
    syncedUtime: number | null;
}
/** A missing range below a stored transaction whose previous transaction is not stored. */
export interface Gap {
    address: string;
    /** The stored transaction whose `prev` link is unsatisfied. */
    aboveLt: bigint;
    /** Where to resume fetching (the missing transaction). */
    prevLt: bigint;
    prevHash: Buffer;
    /** Highest stored lt below the gap, or the address `startLt`. Fetching stops here. */
    floorLt: bigint;
}
/** A transaction handed to consumer code. */
export interface IndexedTx extends TxRecord {
    /** Parsed `@ton/core` transaction (parsed lazily, cached). */
    readonly transaction: Transaction;
}
/** Wraps a stored record for delivery; the `transaction` is parsed on first access. */
export declare function toIndexedTx(record: TxRecord): IndexedTx;
/** Whether two transaction ids are the same; two missing ids are equal. */
export declare function txIdEquals(a: TxId | null | undefined, b: TxId | null | undefined): boolean;
/** The lt up to which every transaction of the address is stored (its watermark input). */
export declare function completeUpTo(state: AddressState): bigint;
/** The lowest `completeUpTo` among `states`: every transaction at or below it is stored. Null if empty. */
export declare function watermarkOf(states: readonly AddressState[]): bigint | null;

// ---- parse/body.d.ts
import type { Cell } from "@ton/core";
import type { MessageBody } from "./types";
export interface ParseBodyOptions {
    /**
     * Whether the message carrying the body has the `bounced` flag. Only then are
     * the `0xffffffff` / `0xfffffffe` prefixes read as bounce bodies.
     */
    bounced?: boolean;
}
/**
 * Decodes a message body: comments, TEP-74 jetton and TEP-62 NFT messages, and
 * bounces. Unrecognized opcodes give `{ kind: "unknown", op }`. Never throws:
 * a body that does not fit its opcode's layout gives `{ kind: "malformed" }`.
 * Bits or refs left over after a known layout are ignored.
 */
export declare function parseMessageBody(body: Cell | null | undefined, options?: ParseBodyOptions): MessageBody;

// ---- parse/deposits.d.ts
/**
 * Deposit checks: the two questions payment processing asks of every
 * transaction, answered with the bounce and failure cases already excluded.
 */
import { Address } from "@ton/core";
import { type ParseTransactionOptions, type TransactionInput } from "./transaction";
import type { ForwardPayload, MessageBody } from "./types";
/** Value an inbound message credited to the account. */
export interface IncomingPayment {
    /** Who sent the TON. */
    sender: Address;
    /** TON value of the inbound message, in nanotons. */
    amount: bigint;
    /**
     * Extra currencies the message carried, by currency id; empty for a TON-only
     * transfer. `amount` does not include them.
     */
    extraCurrencies: Map<number, bigint>;
    /** Text comment, if the body is one; see `body` for binary or encrypted comments. */
    comment: string | null;
    /**
     * The decoded body. Not every credited message is a payment to you: check it
     * is a plain transfer (`empty` or a comment) before crediting, since e.g.
     * `excesses` refunds and the TON attached to jetton notifications arrive the
     * same way.
     */
    body: MessageBody;
    /** Whether the transaction succeeded; `false` for e.g. a deposit to a not yet deployed wallet. */
    success: boolean;
}
/**
 * The value this transaction received, or `null` if it received none.
 *
 * Returns a payment only when the inbound message is internal, from another
 * account, carries TON, is not itself a bounce (returning funds this account
 * sent), and its value was credited to the balance and not bounced back. A
 * failed compute phase does not by itself mean the value was lost — a
 * non-bounceable deposit to an undeployed wallet is skipped by the compute phase
 * and still credited — so such transactions are returned with `success: false`.
 *
 * "Credited" is about this transaction only: the account's own code may have
 * sent value onward in the same transaction (see `parseTransaction(...).valueOut`).
 *
 * Throws, like `parseTransaction`, when a record's BOC is not a transaction or
 * `options.address` is invalid or names another account.
 */
export declare function incomingPayment(input: TransactionInput, options?: ParseTransactionOptions): IncomingPayment | null;
/** One jetton wallet address, or several (e.g. one per accepted jetton), friendly or raw. */
export type JettonWallets = Address | string | Iterable<Address | string>;
/**
 * Which senders of a `transfer_notification` to trust: exactly one of
 * `jettonWallet` (recommended) or `trustAnySender: true`.
 */
export type IncomingJettonTransferOptions = ParseTransactionOptions & ({
    /**
     * This account's own jetton wallet(s) for the jetton(s) you accept; a
     * notification from any other address yields `null`. Get each with the
     * jetton master's `get_wallet_address(owner)`.
     */
    jettonWallet: JettonWallets;
    trustAnySender?: never;
} | {
    /**
     * Accept a notification from any sender. The result's `jettonWallet` is
     * then unverified and must be checked before crediting anything.
     */
    trustAnySender: true;
    jettonWallet?: never;
});
/** Jettons this account received, as reported by a `transfer_notification`. */
export interface IncomingJettonTransfer {
    /**
     * The jetton wallet that sent the notification: one of the `jettonWallet`
     * option's addresses, or UNVERIFIED under `trustAnySender`.
     */
    jettonWallet: Address;
    /** Jetton amount in elementary units. */
    amount: bigint;
    /** Previous owner of the jettons (the payer), as claimed by the jetton wallet. */
    sender: Address | null;
    queryId: bigint;
    /** TON attached to the notification (the transfer's `forward_ton_amount`), in nanotons. */
    tonAmount: bigint;
    /** `malformed` when the payload does not decode; the transfer itself still counts. */
    forwardPayload: ForwardPayload;
    /** Text comment from the forward payload, if it is one. */
    comment: string | null;
}
/**
 * The jetton transfer announced by this transaction's inbound
 * `transfer_notification`, or `null` if there is none or it came from a sender
 * not in `options.jettonWallet`.
 *
 * SECURITY: a `transfer_notification` is an ordinary message that anyone can
 * send with any amount. It only proves a deposit when it comes from this
 * account's own jetton wallet for the expected jetton master, which is why
 * `jettonWallet` is required; `trustAnySender: true` opts out, leaving the check
 * to you.
 *
 * Notifications are only sent when the transfer had a non-zero
 * `forward_ton_amount`; to see every transfer, watch the jetton wallet itself
 * (`jetton-internal-transfer` bodies). The jettons are credited to the jetton
 * wallet before the notification is sent, so the notification transaction's
 * own success or bounce does not undo them.
 *
 * Throws when a record's BOC is not a transaction, `options.address` is invalid
 * or names another account, a `jettonWallet` string is not an address, or
 * neither `jettonWallet` nor `trustAnySender` is given.
 */
export declare function incomingJettonTransfer(input: TransactionInput, options: IncomingJettonTransferOptions): IncomingJettonTransfer | null;

// ---- parse/message.d.ts
import type { Message } from "@ton/core";
import type { ParsedMessage } from "./types";
/** Flattens a `@ton/core` message into a `ParsedMessage` with a decoded body. Never throws. */
export declare function parseMessage(message: Message): ParsedMessage;

// ---- parse/opcodes.d.ts
/**
 * Message opcodes the parser understands: the first 32 bits of a message body.
 *
 * Jetton values are from TEP-74, NFT values from TEP-62, the bounce prefixes from
 * `block.tlb`, and the encrypted comment from the reference wallet
 * (`WalletInterface::EncryptedCommentOp`).
 */
export declare const Op: {
    /** Text or binary comment: `0x00000000` followed by the comment bytes. */
    readonly comment: 0;
    /** Encrypted comment: `0x2167da4b` followed by the cipher text. */
    readonly encryptedComment: 560454219;
    /** Legacy bounced body: `0xffffffff` followed by the first 256 bits of the original body. */
    readonly bounce: 4294967295;
    /** `new_bounce_body#fffffffe` (global version 12), sent when the original message asked for it. */
    readonly newBounce: 4294967294;
    readonly jettonTransfer: 260734629;
    readonly jettonTransferNotification: 1935855772;
    readonly jettonInternalTransfer: 395134233;
    readonly jettonBurn: 1499400124;
    /** Shared by jettons (TEP-74) and NFTs (TEP-62). */
    readonly excesses: 3576854235;
    readonly nftTransfer: 1607220500;
    readonly nftOwnershipAssigned: 85167505;
};
/** First byte of a binary (machine-readable, not for display) comment. */
export declare const BINARY_COMMENT_PREFIX = 255;

// ---- parse/transaction.d.ts
import { Address, type Transaction } from "@ton/core";
import type { TxRecord } from "../core/types";
import type { ParsedTransaction } from "./types";
/** A `@ton/core` transaction, or a stored record / delivered `IndexedTx` holding one. */
export type TransactionInput = Transaction | TxRecord;
export interface ParseTransactionOptions {
    /**
     * The account the transaction belongs to. Optional: it is taken from a
     * `TxRecord`, or else from the transaction's messages. Throws if it is not an
     * address or names a different account (hash, or workchain where the record
     * or the messages tell it) than the transaction's.
     */
    address?: Address | string;
}
/**
 * Summarizes a transaction: outcome, bounce flags, direction, fees and decoded
 * messages. Message bodies never cause a throw (bad ones decode as
 * `{ kind: "malformed" }`); only a record whose BOC is not a transaction, or a
 * mismatching `options.address`, does.
 */
export declare function parseTransaction(input: TransactionInput, options?: ParseTransactionOptions): ParsedTransaction;
/** The `@ton/core` transaction behind any accepted input. */
export declare function toTransaction(input: TransactionInput): Transaction;

// ---- parse/types.d.ts
import type { Address, Cell, ComputeSkipReason, ExternalAddress, Message, Transaction, TransactionDescription } from "@ton/core";
/** `0x00000000` + UTF-8 text, possibly continued through refs ("snake" encoding). */
export interface TextComment {
    kind: "text-comment";
    text: string;
}
/** `0x00000000 0xff` + bytes: a machine-readable comment that is not meant for display. */
export interface BinaryComment {
    kind: "binary-comment";
    /** The bytes after the `0xff` marker. */
    data: Buffer;
}
/** `0x2167da4b` + cipher text. Decrypting needs the recipient's private key. */
export interface EncryptedComment {
    kind: "encrypted-comment";
    /** The cipher text, without the opcode. */
    data: Buffer;
}
export type Comment = TextComment | BinaryComment | EncryptedComment;
/**
 * A body, or part of one, that could not be decoded: a known opcode with a
 * truncated or inconsistent layout, invalid UTF-8 in a comment, and so on.
 */
export interface Malformed {
    kind: "malformed";
    /** The opcode, when at least 32 bits were present. */
    op: number | null;
    reason: string;
}
/** No forward payload, or an empty one. */
export interface EmptyPayload {
    kind: "empty";
}
/** A forward payload that is not a comment, e.g. a call into a DEX. */
export interface OpaquePayload {
    kind: "opaque";
    /** The first 32 bits, when present. */
    op: number | null;
    cell: Cell;
}
/** The `forward_payload:(Either Cell ^Cell)` of a jetton or NFT message. */
export type ForwardPayload = EmptyPayload | Comment | OpaquePayload | Malformed;
/** TEP-74 `transfer#0f8a7ea5`: the owner asks its jetton wallet to send jettons. */
export interface JettonTransfer {
    kind: "jetton-transfer";
    queryId: bigint;
    /** Jetton amount in elementary units. */
    amount: bigint;
    /** Owner (not jetton wallet) that receives the jettons. */
    destination: Address | null;
    responseDestination: Address | null;
    customPayload: Cell | null;
    /** Nanotons the receiving jetton wallet forwards to `destination` with the notification. */
    forwardTonAmount: bigint;
    forwardPayload: ForwardPayload;
}
/**
 * TEP-74 `transfer_notification#7362d09c`: a jetton wallet tells its owner it
 * received jettons.
 *
 * Anyone can send a message with this opcode. It proves nothing unless the
 * message comes from the owner's own jetton wallet of the expected jetton.
 */
export interface JettonTransferNotification {
    kind: "jetton-transfer-notification";
    queryId: bigint;
    amount: bigint;
    /** Previous owner of the jettons, as claimed by the sending jetton wallet. */
    sender: Address | null;
    forwardPayload: ForwardPayload;
}
/** TEP-74 `internal_transfer#178d4519`: jetton wallet to jetton wallet (or minter to wallet). */
export interface JettonInternalTransfer {
    kind: "jetton-internal-transfer";
    queryId: bigint;
    amount: bigint;
    from: Address | null;
    responseAddress: Address | null;
    forwardTonAmount: bigint;
    forwardPayload: ForwardPayload;
}
/** TEP-74 / TEP-62 `excesses#d53276db`: leftover TON returned after an operation. */
export interface Excesses {
    kind: "excesses";
    queryId: bigint;
}
/** TEP-74 `burn#595f07bc`: the owner asks its jetton wallet to burn jettons. */
export interface JettonBurn {
    kind: "jetton-burn";
    queryId: bigint;
    amount: bigint;
    responseDestination: Address | null;
    customPayload: Cell | null;
}
/** TEP-62 `transfer#5fcc3d14`: the owner asks an NFT item to change owner. */
export interface NftTransfer {
    kind: "nft-transfer";
    queryId: bigint;
    newOwner: Address | null;
    responseDestination: Address | null;
    customPayload: Cell | null;
    forwardAmount: bigint;
    forwardPayload: ForwardPayload;
}
/**
 * TEP-62 `ownership_assigned#05138d91`: an NFT item tells its new owner.
 * Like jetton notifications, only meaningful if the sender is a verified item.
 */
export interface NftOwnershipAssigned {
    kind: "nft-ownership-assigned";
    queryId: bigint;
    prevOwner: Address | null;
    forwardPayload: ForwardPayload;
}
/** Legacy bounce: `0xffffffff` + the first 256 bits of the original body. */
export interface LegacyBounce {
    kind: "bounce";
    format: "legacy";
    /** Opcode of the bounced message, when the original body had one. */
    originalOp: number | null;
    /** The 64 bits after the opcode, by convention the query id, when present. */
    originalQueryId: bigint | null;
    /** The returned bits of the original body (at most 256, no refs). */
    originalBody: Cell;
}
/** Why a message bounced under the new bounce format. */
export type BouncePhase = "compute-skipped" | "compute-failed" | "action-failed" | "unknown";
/** `new_bounce_body#fffffffe` (global version 12). */
export interface NewBounce {
    kind: "bounce";
    format: "new";
    originalOp: number | null;
    originalQueryId: bigint | null;
    /** The original body: its root only, or the whole tree if the sender asked for it. */
    originalBody: Cell;
    /** Value of the original message, in nanotons. */
    originalValue: bigint;
    originalCreatedLt: bigint;
    originalCreatedAt: number;
    bouncedBy: BouncePhase;
    /** Compute exit code, action result code, or the negative skip reason (see `block.tlb`). */
    exitCode: number;
    /** Present when the compute phase ran. */
    compute: {
        gasUsed: number;
        vmSteps: number;
    } | null;
}
export type Bounce = LegacyBounce | NewBounce;
/** A body with an opcode this parser does not decode. */
export interface UnknownBody {
    kind: "unknown";
    op: number;
}
/** No body bits and no refs. */
export interface EmptyBody {
    kind: "empty";
}
/** A decoded message body. Decoding never throws; bad input becomes `Malformed`. */
export type MessageBody = EmptyBody | Comment | JettonTransfer | JettonTransferNotification | JettonInternalTransfer | Excesses | JettonBurn | NftTransfer | NftOwnershipAssigned | Bounce | UnknownBody | Malformed;
interface ParsedMessageBase {
    /** First 32 bits of the body, or `null` for a body shorter than that. */
    op: number | null;
    /** Query id of a decoded body that has one. */
    queryId: bigint | null;
    body: MessageBody;
    /** Text of a plain text comment body, otherwise `null`. */
    comment: string | null;
    /** The `@ton/core` message this was parsed from. */
    raw: Message;
}
export interface ParsedInternalMessage extends ParsedMessageBase {
    type: "internal";
    src: Address;
    dest: Address;
    /** Attached value in nanotons. */
    value: bigint;
    /** Extra currencies by id; empty when none are attached. */
    extraCurrencies: Map<number, bigint>;
    /** Whether the message asks to bounce if processing fails. */
    bounce: boolean;
    /** Whether this message is itself a bounce, returning value to its original sender. */
    bounced: boolean;
    fwdFee: bigint;
    /**
     * The field formerly named `ihr_fee`. It has carried no fee since global
     * version 11 and is `extra_flags` since version 12 (bit 0: new bounce format,
     * bit 1: bounce with the full body).
     */
    extraFlags: bigint;
    createdLt: bigint;
    createdAt: number;
}
export interface ParsedExternalInMessage extends ParsedMessageBase {
    type: "external-in";
    src: ExternalAddress | null;
    dest: Address;
    importFee: bigint;
}
export interface ParsedExternalOutMessage extends ParsedMessageBase {
    type: "external-out";
    src: Address;
    dest: ExternalAddress | null;
    createdLt: bigint;
    createdAt: number;
}
export type ParsedMessage = ParsedInternalMessage | ParsedExternalInMessage | ParsedExternalOutMessage;
/**
 * What started the transaction, from the account's point of view:
 * - `incoming`: an internal message from another account;
 * - `outgoing`: an external message, e.g. a wallet owner sending funds;
 * - `self`: an internal message the account sent to itself;
 * - `system`: no inbound message (tick-tock, storage, split/merge).
 */
export type Direction = "incoming" | "outgoing" | "self" | "system";
/** Outcome of the compute phase. */
export type ComputeResult = {
    type: "skipped";
    reason: ComputeSkipReason;
} | {
    type: "vm";
    success: boolean;
    exitCode: number;
    gasUsed: bigint;
};
/** Outcome of the action phase. */
export interface ActionResult {
    success: boolean;
    resultCode: number;
    totalActions: number;
    skippedActions: number;
}
export interface ParsedTransaction {
    /** The account, when it could be determined (option, record, or messages). */
    address: Address | null;
    lt: bigint;
    hash: Buffer;
    /** Unix time of the transaction. */
    utime: number;
    /** Transaction kind, `generic` for ordinary message-driven transactions. */
    type: TransactionDescription["type"];
    /**
     * The transaction did what its code asked: not aborted, the compute phase ran
     * and succeeded, and the action phase (if any) succeeded.
     */
    success: boolean;
    aborted: boolean;
    /** `null` when the transaction kind has no compute phase. */
    compute: ComputeResult | null;
    /** `null` when there was no action phase. */
    action: ActionResult | null;
    /** The inbound message is a bounce: value returning from a failed message this account sent. */
    receivedBounce: boolean;
    /** This transaction bounced the inbound value back to its sender (bounce phase succeeded). */
    bouncedBack: boolean;
    direction: Direction;
    inMessage: ParsedMessage | null;
    outMessages: ParsedMessage[];
    /** Total fees charged to the account, in nanotons. */
    totalFees: bigint;
    /** Value of the inbound internal message, 0 otherwise. */
    valueIn: bigint;
    /** Sum of the values of outbound internal messages. */
    valueOut: bigint;
    /** The `@ton/core` transaction this was parsed from. */
    raw: Transaction;
}
export {};
