// API snapshot of plugins/toncenter/index.d.ts; generated by tests/api-snapshot.test.ts (UPDATE_API_SNAPSHOT=1).

// ---- plugins/toncenter/index.d.ts
/**
 * toncenter as a history plug-in for ton-watch. Imported separately and entirely
 * optional:
 *
 *   import { ToncenterHistory } from "@ton/watch/toncenter";
 *   new TonWatch({ store, source, history: { source: new ToncenterHistory({ apiKey }) } });
 *
 * Experimental: covered by unit tests against a recorded toncenter response and by
 * the free-tier mainnet check in tests/live.test.ts (`LIVE=1`). Paid-plan rate limits
 * and long runs at volume are not tested. Every page is still re-hashed and
 * chain-checked, so a bad answer is rejected rather than stored.
 *
 * @experimental
 * @module
 */
export { ToncenterHistory, type ToncenterHistoryOptions } from "./toncenter-history";

// ---- core/types.d.ts
import { type Transaction } from "@ton/core";
/** Identifies one transaction of an account: logical time + cell hash. */
export interface TxId {
    lt: bigint;
    hash: Buffer;
}
/**
 * A transaction as the indexer stores it. Every account transaction links to the
 * previous one through `prevLt`/`prevHash`; that link is what lets writes land in
 * any order and still be checked for completeness. `prevLt === 0n` marks the
 * account's very first transaction.
 */
export interface TxRecord {
    /** Raw address, `<workchain>:<hex>`. */
    address: string;
    lt: bigint;
    hash: Buffer;
    prevLt: bigint;
    prevHash: Buffer;
    /** Unix time of the block the transaction is in. */
    utime: number;
    /** The transaction cell serialized as a BOC. */
    boc: Buffer;
}
/** What the store knows about one tracked address. */
export interface AddressState {
    /** Raw address, `<workchain>:<hex>`. */
    address: string;
    /** Transactions with `lt <= startLt` are out of scope and never fetched or delivered. */
    startLt: bigint;
    active: boolean;
    /** Newest stored transaction. */
    head: TxId | null;
    /**
     * Newest transaction such that every transaction between `startLt` and it is
     * stored. Ordered delivery never goes past this point.
     */
    frontier: TxId | null;
    /**
     * Chain logical time up to which the address is known complete, even when it
     * had no transactions: no transaction with `lt <= syncedLt` is missing.
     * Used for the cross-address watermark.
     */
    syncedLt: bigint;
    /** Chain unix time at which `syncedLt` was observed, for lag reporting. */
    syncedUtime: number | null;
}
/** A missing range below a stored transaction whose previous transaction is not stored. */
export interface Gap {
    address: string;
    /** The stored transaction whose `prev` link is unsatisfied. */
    aboveLt: bigint;
    /** Where to resume fetching (the missing transaction). */
    prevLt: bigint;
    prevHash: Buffer;
    /** Highest stored lt below the gap, or the address `startLt`. Fetching stops here. */
    floorLt: bigint;
}
/** A transaction handed to consumer code. */
export interface IndexedTx extends TxRecord {
    /** Parsed `@ton/core` transaction (parsed lazily, cached). */
    readonly transaction: Transaction;
}
/** Wraps a stored record for delivery; the `transaction` is parsed on first access. */
export declare function toIndexedTx(record: TxRecord): IndexedTx;
/** Whether two transaction ids are the same; two missing ids are equal. */
export declare function txIdEquals(a: TxId | null | undefined, b: TxId | null | undefined): boolean;
/** The lt up to which every transaction of the address is stored (its watermark input). */
export declare function completeUpTo(state: AddressState): bigint;
/** The lowest `completeUpTo` among `states`: every transaction at or below it is stored. Null if empty. */
export declare function watermarkOf(states: readonly AddressState[]): bigint | null;

// ---- plugins/toncenter/toncenter-history.d.ts
import type { TxId, TxRecord } from "../../core/types";
import type { HistorySource } from "../../source/history";
export interface ToncenterHistoryOptions {
    /** API key; without one toncenter allows 1 request/s. */
    apiKey?: string;
    /** Default https://toncenter.com/api/v2 (testnet: https://testnet.toncenter.com/api/v2). */
    endpoint?: string;
    /** Requests per second to stay under. Default 10 with a key, 1 without. */
    rps?: number;
    /** Transactions per request, up to 1000. Default 256. */
    pageSize?: number;
    /** Per-request timeout. Default 20s. */
    timeoutMs?: number;
    /** Retries on 429/5xx/network errors before giving up on a page. Default 4. */
    retries?: number;
    /** Injectable for tests. */
    fetch?: typeof fetch;
}
/**
 * History plug-in backed by toncenter API v2 `getTransactions` with
 * `archival=true`: the same "newest first, from (lt, hash)" walk as liteservers,
 * but up to 1000 per page and with full history. Pages are raw transaction BOCs,
 * re-hashed and link-checked by the indexer exactly like liteserver pages, so a
 * wrong answer is rejected, not stored.
 *
 * @experimental Not tested against paid-plan rate limits; see the module docs.
 */
export declare class ToncenterHistory implements HistorySource {
    readonly name = "toncenter";
    readonly maxPageSize: number;
    private readonly endpoint;
    private readonly apiKey?;
    private readonly intervalMs;
    private readonly timeoutMs;
    private readonly retries;
    private readonly fetchImpl;
    /** Earliest time the next request may be sent. */
    private nextSlotAt;
    constructor(options?: ToncenterHistoryOptions);
    /** Busy when the next request slot is more than one interval away. */
    busy(): boolean;
    getTransactions(address: string, from: TxId, count: number): Promise<TxRecord[]>;
    /** Waits for the next request slot under the rate limit. */
    private takeSlot;
    /** GET with rate limiting; retries rate limits, 5xx and network errors. */
    private request;
    /** One HTTP round trip; throws a classified `SourceError` for any non-ok answer. */
    private fetchOnce;
}

// ---- source/history.d.ts
import type { TxId, TxRecord } from "../core/types";
/**
 * Optional plug-in that serves account history with bigger pages and deeper
 * retention than liteservers (e.g. `@ton/watch/toncenter`). The indexer only ever
 * asks it for the same thing it asks liteservers — "transactions of this address,
 * newest first, starting at this one" — and checks every page the same way, so a
 * history source can make fetching faster or reach further back, but cannot change
 * what gets stored.
 *
 * @experimental Methods may be added in minor 0.x versions. Exported from
 * `@ton/watch/advanced`.
 */
export interface HistorySource {
    readonly name: string;
    /** Largest page it serves (toncenter: up to 1000). */
    readonly maxPageSize: number;
    getTransactions(address: string, from: TxId, count: number): Promise<TxRecord[]>;
    /** True while it has no spare capacity (rate budget used up); `boost` mode then uses liteservers. */
    busy?(): boolean;
    close?(): Promise<void>;
}
export interface HistoryOptions {
    source: HistorySource;
    /**
     * - `fallback` (default): liteservers first; the history source only for ranges
     *   no liteserver serves any more (older than ~5 weeks on public servers).
     * - `boost`: also use it whenever it has spare capacity, for its bigger pages.
     */
    mode?: "fallback" | "boost";
    /** Off switch without removing the wiring. Default true. */
    enabled?: boolean;
}
